#pragma line 1 "adpcm.c" ::: -10
#pragma line 1 "adpcm.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/patmos/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/home/patmos/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/home/patmos/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "adpcm.c" 2 ::: 184
#pragma line 1 "./adpcm.h" 1 ::: 251
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 256
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 284
#pragma line 122 "/usr/include/features.h" 3 4 ::: 381
#pragma line 156 "/usr/include/features.h" 3 4 ::: 406
#pragma line 180 "/usr/include/features.h" 3 4 ::: 408
#pragma line 191 "/usr/include/features.h" 3 4 ::: 411
#pragma line 343 "/usr/include/features.h" 3 4 ::: 442
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 446
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 481
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 488
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 511
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 552
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 558
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 576
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 582
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 586
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 588
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 592
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 602
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 655
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 696
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 721
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 745
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 746
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 748
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 750
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 751
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 776
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 787
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 792
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 793
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 794
#pragma line 1 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 800
#pragma line 56 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 841
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 844
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 846
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 874
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 876
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 878
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 939
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 946
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 964
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 969
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 980
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1049
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1063
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1066
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1067
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1099
#pragma line 1 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1115
#pragma line 56 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1140
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1143
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1148
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1170
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1191
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1194
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1205
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1215
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1217
#pragma line 1 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1221
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1270
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1271
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1277
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1279
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1299
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1310
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1351
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1381
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1407
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1411
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1426
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1438
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1444
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1446
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1456
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1478
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1494
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1511
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1543
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1589
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1603
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1606
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1682
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1721
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1762
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1875
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1938
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1987
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1998
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2028
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2056
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2088
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2100
#pragma line 6 "./adpcm.h" 2 ::: 2103
#pragma line 24 "./adpcm.h" ::: 2104
#pragma line 67 "adpcm.c" 2 ::: 2197
