#pragma line 1 "adpcm_lib.c" ::: 0
#pragma line 1 "adpcm_lib.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/home/patmos/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/home/patmos/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 421 "/home/patmos/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "adpcm_lib.c" 2 ::: 194
#pragma line 1 "./adpcm.h" 1 ::: 196
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 201
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 229
#pragma line 122 "/usr/include/features.h" 3 4 ::: 326
#pragma line 156 "/usr/include/features.h" 3 4 ::: 351
#pragma line 180 "/usr/include/features.h" 3 4 ::: 353
#pragma line 191 "/usr/include/features.h" 3 4 ::: 356
#pragma line 343 "/usr/include/features.h" 3 4 ::: 387
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 391
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 426
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 433
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 456
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 497
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 503
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 521
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 527
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 531
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 533
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 537
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 547
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 600
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 641
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 666
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 690
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 691
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 693
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 695
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 696
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 721
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 732
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 737
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 738
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 739
#pragma line 1 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 745
#pragma line 56 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 786
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 789
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 791
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 819
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 821
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 823
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 884
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 891
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 909
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 914
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 925
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 994
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1008
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1011
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1012
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1044
#pragma line 1 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1060
#pragma line 56 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1085
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1088
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1093
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1115
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1136
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1139
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1150
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1160
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1162
#pragma line 1 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1166
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1215
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1216
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1222
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1224
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1244
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1255
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1296
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1326
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1352
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1356
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1371
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1383
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1389
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1391
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1401
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1423
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1439
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1456
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1488
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1534
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1548
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1551
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1627
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1666
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1707
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1820
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1883
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1932
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1943
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1973
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2001
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2033
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2045
#pragma line 6 "./adpcm.h" 2 ::: 2048
#pragma line 24 "./adpcm.h" ::: 2049
#pragma line 3 "adpcm_lib.c" 2 ::: 2142
