#pragma line 1 "adpcm_lib.c" ::: -10
#pragma line 1 "adpcm_lib.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/patmos/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/home/patmos/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/home/patmos/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "adpcm_lib.c" 2 ::: 184
#pragma line 1 "./adpcm.h" 1 ::: 186
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 191
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 219
#pragma line 122 "/usr/include/features.h" 3 4 ::: 316
#pragma line 156 "/usr/include/features.h" 3 4 ::: 341
#pragma line 180 "/usr/include/features.h" 3 4 ::: 343
#pragma line 191 "/usr/include/features.h" 3 4 ::: 346
#pragma line 343 "/usr/include/features.h" 3 4 ::: 377
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 381
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 416
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 423
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 446
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 487
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 493
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 511
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 517
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 521
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 523
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 527
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 537
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 590
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 631
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 656
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 680
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 681
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 683
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 685
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 686
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 711
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 722
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 727
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 728
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 729
#pragma line 1 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 735
#pragma line 56 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 776
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 779
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 781
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 809
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 811
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 813
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 874
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 881
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 899
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 904
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 915
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 984
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 998
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1001
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1002
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1034
#pragma line 1 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1050
#pragma line 56 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1075
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1078
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1083
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1105
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1126
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1129
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1140
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1150
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1152
#pragma line 1 "/home/patmos/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1156
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1205
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1206
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1212
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1214
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1234
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1245
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1286
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1316
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1342
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1346
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1361
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1373
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1379
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1381
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1391
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1413
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1429
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1446
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1478
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1524
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1538
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1541
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1617
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1656
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1697
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1810
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1873
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1922
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1933
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1963
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1991
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2023
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2035
#pragma line 6 "./adpcm.h" 2 ::: 2038
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 2039
#pragma line 30 "/usr/include/math.h" 3 4 ::: 2061
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 2064
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 2090
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 2122
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 2123
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 2128
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 2153
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 2155
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 2180
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 2181
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 2200
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 2204
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 2228
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 2232
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 2257
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 2262
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 2279
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 2285
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 2292
#pragma line 83 "/usr/include/math.h" 3 4 ::: 2298
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 2299
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2376
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2406
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2647
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 2650
#pragma line 93 "/usr/include/math.h" 3 4 ::: 2651
#pragma line 104 "/usr/include/math.h" 3 4 ::: 2654
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 2655
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2732
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2762
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 3003
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 3006
#pragma line 139 "/usr/include/math.h" 3 4 ::: 3007
#pragma line 151 "/usr/include/math.h" 3 4 ::: 3010
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 3011
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 3088
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 3118
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 3359
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 3362
#pragma line 167 "/usr/include/math.h" 3 4 ::: 3363
#pragma line 248 "/usr/include/math.h" 3 4 ::: 3430
#pragma line 268 "/usr/include/math.h" 3 4 ::: 3432
#pragma line 282 "/usr/include/math.h" 3 4 ::: 3434
#pragma line 304 "/usr/include/math.h" 3 4 ::: 3444
#pragma line 318 "/usr/include/math.h" 3 4 ::: 3446
#pragma line 346 "/usr/include/math.h" 3 4 ::: 3454
#pragma line 411 "/usr/include/math.h" 3 4 ::: 3508
#pragma line 428 "/usr/include/math.h" 3 4 ::: 3510
#pragma line 448 "/usr/include/math.h" 3 4 ::: 3514
#pragma line 470 "/usr/include/math.h" 3 4 ::: 3529
#pragma line 7 "./adpcm.h" 2 ::: 3585
#pragma line 25 "./adpcm.h" ::: 3586
#pragma line 3 "adpcm_lib.c" 2 ::: 3679
