#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("r_Addr_A", 32, hls_out, 0, "bram", "mem_address", 1),
	Port_Property("r_EN_A", 1, hls_out, 0, "bram", "mem_ce", 1),
	Port_Property("r_WEN_A", 4, hls_out, 0, "bram", "mem_we", 1),
	Port_Property("r_Din_A", 32, hls_out, 0, "bram", "mem_din", 1),
	Port_Property("r_Dout_A", 32, hls_in, 0, "bram", "mem_dout", 1),
	Port_Property("r_Clk_A", 1, hls_out, 0, "bram", "mem_clk", 1),
	Port_Property("r_Rst_A", 1, hls_out, 0, "bram", "mem_rst", 1),
	Port_Property("y_Addr_A", 32, hls_out, 1, "bram", "mem_address", 1),
	Port_Property("y_EN_A", 1, hls_out, 1, "bram", "mem_ce", 1),
	Port_Property("y_WEN_A", 4, hls_out, 1, "bram", "mem_we", 1),
	Port_Property("y_Din_A", 32, hls_out, 1, "bram", "mem_din", 1),
	Port_Property("y_Dout_A", 32, hls_in, 1, "bram", "mem_dout", 1),
	Port_Property("y_Clk_A", 1, hls_out, 1, "bram", "mem_clk", 1),
	Port_Property("y_Rst_A", 1, hls_out, 1, "bram", "mem_rst", 1),
	Port_Property("H_Addr_A", 32, hls_out, 2, "bram", "mem_address", 1),
	Port_Property("H_EN_A", 1, hls_out, 2, "bram", "mem_ce", 1),
	Port_Property("H_WEN_A", 4, hls_out, 2, "bram", "mem_we", 1),
	Port_Property("H_Din_A", 32, hls_out, 2, "bram", "mem_din", 1),
	Port_Property("H_Dout_A", 32, hls_in, 2, "bram", "mem_dout", 1),
	Port_Property("H_Clk_A", 1, hls_out, 2, "bram", "mem_clk", 1),
	Port_Property("H_Rst_A", 1, hls_out, 2, "bram", "mem_rst", 1),
	Port_Property("F_Addr_A", 32, hls_out, 3, "bram", "mem_address", 1),
	Port_Property("F_EN_A", 1, hls_out, 3, "bram", "mem_ce", 1),
	Port_Property("F_WEN_A", 4, hls_out, 3, "bram", "mem_we", 1),
	Port_Property("F_Din_A", 32, hls_out, 3, "bram", "mem_din", 1),
	Port_Property("F_Dout_A", 32, hls_in, 3, "bram", "mem_dout", 1),
	Port_Property("F_Clk_A", 1, hls_out, 3, "bram", "mem_clk", 1),
	Port_Property("F_Rst_A", 1, hls_out, 3, "bram", "mem_rst", 1),
};
const char* HLS_Design_Meta::dut_name = "filterbank_core_hwa";
