#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("fir2dim_coefficients_address0", 4, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("fir2dim_coefficients_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("fir2dim_coefficients_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("fir2dim_coefficients_address1", 4, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("fir2dim_coefficients_ce1", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("fir2dim_coefficients_q1", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("fir2dim_image_address0", 4, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("fir2dim_image_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("fir2dim_image_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("fir2dim_image_d0", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("fir2dim_image_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("fir2dim_image_address1", 4, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("fir2dim_image_ce1", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("fir2dim_image_we1", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("fir2dim_image_d1", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("fir2dim_image_q1", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("fir2dim_array_address0", 6, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("fir2dim_array_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("fir2dim_array_q0", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("fir2dim_array_address1", 6, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("fir2dim_array_ce1", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("fir2dim_array_q1", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("fir2dim_output_address0", 4, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("fir2dim_output_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("fir2dim_output_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("fir2dim_output_d0", 32, hls_out, 3, "ap_memory", "mem_din", 1),
};
const char* HLS_Design_Meta::dut_name = "fir2dim_hwa";
