// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matmul_hw.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matmul_hw::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matmul_hw::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<18> matmul_hw::ap_ST_fsm_state1 = "1";
const sc_lv<18> matmul_hw::ap_ST_fsm_state2 = "10";
const sc_lv<18> matmul_hw::ap_ST_fsm_state3 = "100";
const sc_lv<18> matmul_hw::ap_ST_fsm_state4 = "1000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state5 = "10000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state6 = "100000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state7 = "1000000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state8 = "10000000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state9 = "100000000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state10 = "1000000000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state11 = "10000000000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state12 = "100000000000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<18> matmul_hw::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<32> matmul_hw::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> matmul_hw::ap_const_lv1_1 = "1";
const sc_lv<32> matmul_hw::ap_const_lv32_1 = "1";
const sc_lv<1> matmul_hw::ap_const_lv1_0 = "0";
const sc_lv<32> matmul_hw::ap_const_lv32_2 = "10";
const sc_lv<32> matmul_hw::ap_const_lv32_3 = "11";
const sc_lv<32> matmul_hw::ap_const_lv32_4 = "100";
const sc_lv<32> matmul_hw::ap_const_lv32_5 = "101";
const sc_lv<32> matmul_hw::ap_const_lv32_6 = "110";
const sc_lv<32> matmul_hw::ap_const_lv32_7 = "111";
const sc_lv<32> matmul_hw::ap_const_lv32_8 = "1000";
const sc_lv<32> matmul_hw::ap_const_lv32_9 = "1001";
const sc_lv<32> matmul_hw::ap_const_lv32_C = "1100";
const sc_lv<32> matmul_hw::ap_const_lv32_D = "1101";
const sc_lv<32> matmul_hw::ap_const_lv32_E = "1110";
const sc_lv<32> matmul_hw::ap_const_lv32_F = "1111";
const sc_lv<32> matmul_hw::ap_const_lv32_10 = "10000";
const sc_lv<5> matmul_hw::ap_const_lv5_0 = "00000";
const sc_lv<3> matmul_hw::ap_const_lv3_0 = "000";
const sc_lv<4> matmul_hw::ap_const_lv4_0 = "0000";
const sc_lv<4> matmul_hw::ap_const_lv4_F = "1111";
const sc_lv<5> matmul_hw::ap_const_lv5_10 = "10000";
const sc_lv<5> matmul_hw::ap_const_lv5_1 = "1";
const sc_lv<3> matmul_hw::ap_const_lv3_1 = "1";
const sc_lv<3> matmul_hw::ap_const_lv3_4 = "100";
const sc_lv<2> matmul_hw::ap_const_lv2_0 = "00";
const sc_lv<59> matmul_hw::ap_const_lv59_0 = "00000000000000000000000000000000000000000000000000000000000";
const sc_lv<5> matmul_hw::ap_const_lv5_2 = "10";
const sc_lv<5> matmul_hw::ap_const_lv5_3 = "11";
const sc_lv<61> matmul_hw::ap_const_lv61_2 = "10";
const sc_lv<5> matmul_hw::ap_const_lv5_14 = "10100";
const sc_lv<2> matmul_hw::ap_const_lv2_2 = "10";
const sc_lv<2> matmul_hw::ap_const_lv2_1 = "1";
const sc_lv<61> matmul_hw::ap_const_lv61_3 = "11";
const sc_lv<6> matmul_hw::ap_const_lv6_1C = "11100";
const sc_lv<32> matmul_hw::ap_const_lv32_A = "1010";
const sc_lv<32> matmul_hw::ap_const_lv32_11 = "10001";

matmul_hw::matmul_hw(sc_module_name name) : sc_module(name), mVcdFile(0) {
    matmul_hw_mux_42_bkb_U1 = new matmul_hw_mux_42_bkb<1,1,32,32,32,32,2,32>("matmul_hw_mux_42_bkb_U1");
    matmul_hw_mux_42_bkb_U1->din1(tmp_6_fu_591_p1);
    matmul_hw_mux_42_bkb_U1->din2(tmp_6_fu_591_p2);
    matmul_hw_mux_42_bkb_U1->din3(tmp_6_fu_591_p3);
    matmul_hw_mux_42_bkb_U1->din4(tmp_6_fu_591_p4);
    matmul_hw_mux_42_bkb_U1->din5(tmp_reg_1357);
    matmul_hw_mux_42_bkb_U1->dout(tmp_6_fu_591_p6);
    matmul_hw_mul_32scud_U2 = new matmul_hw_mul_32scud<1,6,32,32,32>("matmul_hw_mul_32scud_U2");
    matmul_hw_mul_32scud_U2->clk(ap_clk);
    matmul_hw_mul_32scud_U2->reset(ap_rst);
    matmul_hw_mul_32scud_U2->din0(tmp_6_reg_1432);
    matmul_hw_mul_32scud_U2->din1(a_row_0_1_reg_1383);
    matmul_hw_mul_32scud_U2->ce(ap_var_for_const0);
    matmul_hw_mul_32scud_U2->dout(grp_fu_755_p2);
    matmul_hw_mux_42_bkb_U3 = new matmul_hw_mux_42_bkb<1,1,32,32,32,32,2,32>("matmul_hw_mux_42_bkb_U3");
    matmul_hw_mux_42_bkb_U3->din1(tmp_7_fu_759_p1);
    matmul_hw_mux_42_bkb_U3->din2(tmp_7_fu_759_p2);
    matmul_hw_mux_42_bkb_U3->din3(tmp_7_fu_759_p3);
    matmul_hw_mux_42_bkb_U3->din4(tmp_7_fu_759_p4);
    matmul_hw_mux_42_bkb_U3->din5(tmp_reg_1357);
    matmul_hw_mux_42_bkb_U3->dout(tmp_7_fu_759_p6);
    matmul_hw_mul_32scud_U4 = new matmul_hw_mul_32scud<1,6,32,32,32>("matmul_hw_mul_32scud_U4");
    matmul_hw_mul_32scud_U4->clk(ap_clk);
    matmul_hw_mul_32scud_U4->reset(ap_rst);
    matmul_hw_mul_32scud_U4->din0(tmp_7_reg_1442);
    matmul_hw_mul_32scud_U4->din1(a_row_1_1_reg_1378);
    matmul_hw_mul_32scud_U4->ce(ap_var_for_const0);
    matmul_hw_mul_32scud_U4->dout(grp_fu_909_p2);
    matmul_hw_mux_42_bkb_U5 = new matmul_hw_mux_42_bkb<1,1,32,32,32,32,2,32>("matmul_hw_mux_42_bkb_U5");
    matmul_hw_mux_42_bkb_U5->din1(tmp_9_fu_913_p1);
    matmul_hw_mux_42_bkb_U5->din2(tmp_9_fu_913_p2);
    matmul_hw_mux_42_bkb_U5->din3(tmp_9_fu_913_p3);
    matmul_hw_mux_42_bkb_U5->din4(tmp_9_fu_913_p4);
    matmul_hw_mux_42_bkb_U5->din5(tmp_reg_1357);
    matmul_hw_mux_42_bkb_U5->dout(tmp_9_fu_913_p6);
    matmul_hw_mul_32scud_U6 = new matmul_hw_mul_32scud<1,6,32,32,32>("matmul_hw_mul_32scud_U6");
    matmul_hw_mul_32scud_U6->clk(ap_clk);
    matmul_hw_mul_32scud_U6->reset(ap_rst);
    matmul_hw_mul_32scud_U6->din0(tmp_9_reg_1452);
    matmul_hw_mul_32scud_U6->din1(a_row_2_1_reg_1373);
    matmul_hw_mul_32scud_U6->ce(ap_var_for_const0);
    matmul_hw_mul_32scud_U6->dout(grp_fu_1049_p2);
    matmul_hw_mux_42_bkb_U7 = new matmul_hw_mux_42_bkb<1,1,32,32,32,32,2,32>("matmul_hw_mux_42_bkb_U7");
    matmul_hw_mux_42_bkb_U7->din1(tmp_10_fu_1053_p1);
    matmul_hw_mux_42_bkb_U7->din2(tmp_10_fu_1053_p2);
    matmul_hw_mux_42_bkb_U7->din3(tmp_10_fu_1053_p3);
    matmul_hw_mux_42_bkb_U7->din4(tmp_10_fu_1053_p4);
    matmul_hw_mux_42_bkb_U7->din5(tmp_reg_1357);
    matmul_hw_mux_42_bkb_U7->dout(tmp_10_fu_1053_p6);
    matmul_hw_mul_32scud_U8 = new matmul_hw_mul_32scud<1,6,32,32,32>("matmul_hw_mul_32scud_U8");
    matmul_hw_mul_32scud_U8->clk(ap_clk);
    matmul_hw_mul_32scud_U8->reset(ap_rst);
    matmul_hw_mul_32scud_U8->din0(tmp_10_reg_1457);
    matmul_hw_mul_32scud_U8->din1(a_row_3_1_reg_1368);
    matmul_hw_mul_32scud_U8->ce(ap_var_for_const0);
    matmul_hw_mul_32scud_U8->dout(grp_fu_1086_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_Addr_A);
    sensitive << ( a_Addr_A_orig );

    SC_METHOD(thread_a_Addr_A_orig);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_2_fu_338_p1 );
    sensitive << ( tmp_11_fu_348_p3 );
    sensitive << ( tmp_13_fu_362_p3 );
    sensitive << ( tmp_15_fu_376_p3 );
    sensitive << ( tmp_16_fu_392_p3 );
    sensitive << ( tmp_19_cast_fu_471_p1 );
    sensitive << ( tmp_18_fu_656_p3 );
    sensitive << ( tmp_21_cast_fu_813_p1 );
    sensitive << ( tmp_22_cast_fu_1116_p1 );

    SC_METHOD(thread_a_Clk_A);
    sensitive << ( ap_clk );

    SC_METHOD(thread_a_Din_A);
    sensitive << ( tmp2_reg_1477 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp3_fu_1121_p2 );

    SC_METHOD(thread_a_EN_A);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_a_Rst_A);
    sensitive << ( ap_rst );

    SC_METHOD(thread_a_WEN_A);
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_a_row_0_1_fu_455_p3);
    sensitive << ( a_row_0_reg_1312 );
    sensitive << ( a_row_0_2_fu_88 );
    sensitive << ( tmp_5_fu_429_p2 );

    SC_METHOD(thread_a_row_1_1_fu_448_p3);
    sensitive << ( a_row_1_reg_1322 );
    sensitive << ( a_row_1_2_fu_92 );
    sensitive << ( tmp_5_fu_429_p2 );

    SC_METHOD(thread_a_row_2_1_fu_441_p3);
    sensitive << ( a_row_2_reg_1332 );
    sensitive << ( a_row_2_2_fu_96 );
    sensitive << ( tmp_5_fu_429_p2 );

    SC_METHOD(thread_a_row_3_1_fu_434_p3);
    sensitive << ( a_row_3_reg_1347 );
    sensitive << ( a_row_3_2_fu_100 );
    sensitive << ( tmp_5_fu_429_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_b_copy_0_3_14_fu_547_p3);
    sensitive << ( sel_tmp4_fu_502_p2 );
    sensitive << ( b_copy_0_3_8_fu_108 );
    sensitive << ( b_copy_0_3_9_fu_539_p3 );

    SC_METHOD(thread_b_copy_0_3_15_fu_555_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp4_fu_502_p2 );
    sensitive << ( b_copy_0_3_11_fu_104 );

    SC_METHOD(thread_b_copy_0_3_16_fu_570_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_0_3_12_fu_112 );
    sensitive << ( b_copy_0_3_7_fu_531_p3 );

    SC_METHOD(thread_b_copy_0_3_17_fu_577_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_0_3_8_fu_108 );
    sensitive << ( b_copy_0_3_14_fu_547_p3 );

    SC_METHOD(thread_b_copy_0_3_18_fu_584_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_0_3_11_fu_104 );
    sensitive << ( b_copy_0_3_15_fu_555_p3 );

    SC_METHOD(thread_b_copy_0_3_2_fu_507_p3);
    sensitive << ( sel_tmp4_fu_502_p2 );
    sensitive << ( b_copy_0_3_1_fu_116 );
    sensitive << ( b_copy_0_3_4_fu_494_p3 );

    SC_METHOD(thread_b_copy_0_3_3_fu_563_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_0_3_1_fu_116 );
    sensitive << ( b_copy_0_3_2_fu_507_p3 );

    SC_METHOD(thread_b_copy_0_3_4_fu_494_p3);
    sensitive << ( sel_tmp2_fu_489_p2 );
    sensitive << ( b_copy_0_3_1_fu_116 );
    sensitive << ( b_copy_0_3_fu_481_p3 );

    SC_METHOD(thread_b_copy_0_3_5_fu_515_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp_fu_476_p2 );
    sensitive << ( b_copy_0_3_12_fu_112 );

    SC_METHOD(thread_b_copy_0_3_6_fu_523_p3);
    sensitive << ( sel_tmp2_fu_489_p2 );
    sensitive << ( b_copy_0_3_12_fu_112 );
    sensitive << ( b_copy_0_3_5_fu_515_p3 );

    SC_METHOD(thread_b_copy_0_3_7_fu_531_p3);
    sensitive << ( sel_tmp4_fu_502_p2 );
    sensitive << ( b_copy_0_3_12_fu_112 );
    sensitive << ( b_copy_0_3_6_fu_523_p3 );

    SC_METHOD(thread_b_copy_0_3_9_fu_539_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp2_fu_489_p2 );
    sensitive << ( b_copy_0_3_8_fu_108 );

    SC_METHOD(thread_b_copy_0_3_fu_481_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp_fu_476_p2 );
    sensitive << ( b_copy_0_3_1_fu_116 );

    SC_METHOD(thread_b_copy_1_3_14_fu_713_p3);
    sensitive << ( sel_tmp4_reg_1416 );
    sensitive << ( b_copy_1_3_8_fu_124 );
    sensitive << ( b_copy_1_3_9_fu_706_p3 );

    SC_METHOD(thread_b_copy_1_3_15_fu_720_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp4_reg_1416 );
    sensitive << ( b_copy_1_3_11_fu_120 );

    SC_METHOD(thread_b_copy_1_3_16_fu_734_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_1_3_12_fu_128 );
    sensitive << ( b_copy_1_3_7_fu_699_p3 );

    SC_METHOD(thread_b_copy_1_3_17_fu_741_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_1_3_8_fu_124 );
    sensitive << ( b_copy_1_3_14_fu_713_p3 );

    SC_METHOD(thread_b_copy_1_3_18_fu_748_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_1_3_11_fu_120 );
    sensitive << ( b_copy_1_3_15_fu_720_p3 );

    SC_METHOD(thread_b_copy_1_3_2_fu_678_p3);
    sensitive << ( sel_tmp4_reg_1416 );
    sensitive << ( b_copy_1_3_1_fu_132 );
    sensitive << ( b_copy_1_3_4_fu_671_p3 );

    SC_METHOD(thread_b_copy_1_3_3_fu_727_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_1_3_1_fu_132 );
    sensitive << ( b_copy_1_3_2_fu_678_p3 );

    SC_METHOD(thread_b_copy_1_3_4_fu_671_p3);
    sensitive << ( sel_tmp2_reg_1403 );
    sensitive << ( b_copy_1_3_1_fu_132 );
    sensitive << ( b_copy_1_3_fu_664_p3 );

    SC_METHOD(thread_b_copy_1_3_5_fu_685_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp_reg_1393 );
    sensitive << ( b_copy_1_3_12_fu_128 );

    SC_METHOD(thread_b_copy_1_3_6_fu_692_p3);
    sensitive << ( sel_tmp2_reg_1403 );
    sensitive << ( b_copy_1_3_12_fu_128 );
    sensitive << ( b_copy_1_3_5_fu_685_p3 );

    SC_METHOD(thread_b_copy_1_3_7_fu_699_p3);
    sensitive << ( sel_tmp4_reg_1416 );
    sensitive << ( b_copy_1_3_12_fu_128 );
    sensitive << ( b_copy_1_3_6_fu_692_p3 );

    SC_METHOD(thread_b_copy_1_3_9_fu_706_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp2_reg_1403 );
    sensitive << ( b_copy_1_3_8_fu_124 );

    SC_METHOD(thread_b_copy_1_3_fu_664_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp_reg_1393 );
    sensitive << ( b_copy_1_3_1_fu_132 );

    SC_METHOD(thread_b_copy_2_3_14_fu_867_p3);
    sensitive << ( sel_tmp4_reg_1416 );
    sensitive << ( b_copy_2_3_8_fu_140 );
    sensitive << ( b_copy_2_3_9_fu_860_p3 );

    SC_METHOD(thread_b_copy_2_3_15_fu_874_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp4_reg_1416 );
    sensitive << ( b_copy_2_3_11_fu_136 );

    SC_METHOD(thread_b_copy_2_3_16_fu_888_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_2_3_12_fu_144 );
    sensitive << ( b_copy_2_3_7_fu_853_p3 );

    SC_METHOD(thread_b_copy_2_3_17_fu_895_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_2_3_8_fu_140 );
    sensitive << ( b_copy_2_3_14_fu_867_p3 );

    SC_METHOD(thread_b_copy_2_3_18_fu_902_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_2_3_11_fu_136 );
    sensitive << ( b_copy_2_3_15_fu_874_p3 );

    SC_METHOD(thread_b_copy_2_3_2_fu_832_p3);
    sensitive << ( sel_tmp4_reg_1416 );
    sensitive << ( b_copy_2_3_1_fu_148 );
    sensitive << ( b_copy_2_3_4_fu_825_p3 );

    SC_METHOD(thread_b_copy_2_3_3_fu_881_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_2_3_1_fu_148 );
    sensitive << ( b_copy_2_3_2_fu_832_p3 );

    SC_METHOD(thread_b_copy_2_3_4_fu_825_p3);
    sensitive << ( sel_tmp2_reg_1403 );
    sensitive << ( b_copy_2_3_1_fu_148 );
    sensitive << ( b_copy_2_3_fu_818_p3 );

    SC_METHOD(thread_b_copy_2_3_5_fu_839_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp_reg_1393 );
    sensitive << ( b_copy_2_3_12_fu_144 );

    SC_METHOD(thread_b_copy_2_3_6_fu_846_p3);
    sensitive << ( sel_tmp2_reg_1403 );
    sensitive << ( b_copy_2_3_12_fu_144 );
    sensitive << ( b_copy_2_3_5_fu_839_p3 );

    SC_METHOD(thread_b_copy_2_3_7_fu_853_p3);
    sensitive << ( sel_tmp4_reg_1416 );
    sensitive << ( b_copy_2_3_12_fu_144 );
    sensitive << ( b_copy_2_3_6_fu_846_p3 );

    SC_METHOD(thread_b_copy_2_3_9_fu_860_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp2_reg_1403 );
    sensitive << ( b_copy_2_3_8_fu_140 );

    SC_METHOD(thread_b_copy_2_3_fu_818_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp_reg_1393 );
    sensitive << ( b_copy_2_3_1_fu_148 );

    SC_METHOD(thread_b_copy_3_3_14_fu_1007_p3);
    sensitive << ( sel_tmp4_reg_1416 );
    sensitive << ( b_copy_3_3_8_fu_156 );
    sensitive << ( b_copy_3_3_9_fu_1000_p3 );

    SC_METHOD(thread_b_copy_3_3_15_fu_1014_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp4_reg_1416 );
    sensitive << ( b_copy_3_3_11_fu_152 );

    SC_METHOD(thread_b_copy_3_3_16_fu_1028_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_3_3_12_fu_160 );
    sensitive << ( b_copy_3_3_7_fu_993_p3 );

    SC_METHOD(thread_b_copy_3_3_17_fu_1035_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_3_3_8_fu_156 );
    sensitive << ( b_copy_3_3_14_fu_1007_p3 );

    SC_METHOD(thread_b_copy_3_3_18_fu_1042_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_3_3_11_fu_152 );
    sensitive << ( b_copy_3_3_15_fu_1014_p3 );

    SC_METHOD(thread_b_copy_3_3_2_fu_972_p3);
    sensitive << ( sel_tmp4_reg_1416 );
    sensitive << ( b_copy_3_3_1_fu_164 );
    sensitive << ( b_copy_3_3_4_fu_965_p3 );

    SC_METHOD(thread_b_copy_3_3_3_fu_1021_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( b_copy_3_3_1_fu_164 );
    sensitive << ( b_copy_3_3_2_fu_972_p3 );

    SC_METHOD(thread_b_copy_3_3_4_fu_965_p3);
    sensitive << ( sel_tmp2_reg_1403 );
    sensitive << ( b_copy_3_3_1_fu_164 );
    sensitive << ( b_copy_3_3_fu_958_p3 );

    SC_METHOD(thread_b_copy_3_3_5_fu_979_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp_reg_1393 );
    sensitive << ( b_copy_3_3_12_fu_160 );

    SC_METHOD(thread_b_copy_3_3_6_fu_986_p3);
    sensitive << ( sel_tmp2_reg_1403 );
    sensitive << ( b_copy_3_3_12_fu_160 );
    sensitive << ( b_copy_3_3_5_fu_979_p3 );

    SC_METHOD(thread_b_copy_3_3_7_fu_993_p3);
    sensitive << ( sel_tmp4_reg_1416 );
    sensitive << ( b_copy_3_3_12_fu_160 );
    sensitive << ( b_copy_3_3_6_fu_986_p3 );

    SC_METHOD(thread_b_copy_3_3_9_fu_1000_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp2_reg_1403 );
    sensitive << ( b_copy_3_3_8_fu_156 );

    SC_METHOD(thread_b_copy_3_3_fu_958_p3);
    sensitive << ( a_Dout_A );
    sensitive << ( sel_tmp_reg_1393 );
    sensitive << ( b_copy_3_3_1_fu_164 );

    SC_METHOD(thread_exitcond_flatten_fu_278_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( indvar_flatten_reg_244 );

    SC_METHOD(thread_exitcond_fu_296_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten_fu_278_p2 );
    sensitive << ( j_reg_266 );

    SC_METHOD(thread_i_1_fu_290_p2);
    sensitive << ( i_reg_255 );

    SC_METHOD(thread_indvar_flatten_next_fu_284_p2);
    sensitive << ( indvar_flatten_reg_244 );

    SC_METHOD(thread_j_1_fu_1131_p2);
    sensitive << ( j_mid2_reg_1337 );

    SC_METHOD(thread_j_mid2_fu_385_p3);
    sensitive << ( exitcond_reg_1264 );
    sensitive << ( j_reg_266 );

    SC_METHOD(thread_sel_tmp2_fu_489_p2);
    sensitive << ( tmp_reg_1357 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_sel_tmp4_fu_502_p2);
    sensitive << ( tmp_reg_1357 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_sel_tmp_fu_476_p2);
    sensitive << ( tmp_reg_1357 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_tmp1_fu_308_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten_fu_278_p2 );
    sensitive << ( i_reg_255 );

    SC_METHOD(thread_tmp2_fu_1090_p2);
    sensitive << ( tmp_s_reg_1462 );
    sensitive << ( tmp_11_1_reg_1467 );

    SC_METHOD(thread_tmp3_fu_1121_p2);
    sensitive << ( tmp_11_2_reg_1472 );
    sensitive << ( tmp_11_3_reg_1482 );

    SC_METHOD(thread_tmp_10_fu_1053_p1);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( b_copy_3_3_11_fu_152 );
    sensitive << ( b_copy_3_3_15_fu_1014_p3 );

    SC_METHOD(thread_tmp_10_fu_1053_p2);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( b_copy_3_3_8_fu_156 );
    sensitive << ( b_copy_3_3_14_fu_1007_p3 );

    SC_METHOD(thread_tmp_10_fu_1053_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( b_copy_3_3_12_fu_160 );
    sensitive << ( b_copy_3_3_7_fu_993_p3 );

    SC_METHOD(thread_tmp_10_fu_1053_p4);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( b_copy_3_3_1_fu_164 );
    sensitive << ( b_copy_3_3_2_fu_972_p3 );

    SC_METHOD(thread_tmp_11_fu_348_p3);
    sensitive << ( tmp_8_fu_343_p2 );

    SC_METHOD(thread_tmp_12_fu_357_p2);
    sensitive << ( tmp_3_reg_1295 );

    SC_METHOD(thread_tmp_13_fu_362_p3);
    sensitive << ( tmp_12_fu_357_p2 );

    SC_METHOD(thread_tmp_14_fu_371_p2);
    sensitive << ( tmp_3_reg_1295 );

    SC_METHOD(thread_tmp_15_fu_376_p3);
    sensitive << ( tmp_14_fu_371_p2 );

    SC_METHOD(thread_tmp_16_fu_392_p3);
    sensitive << ( j_mid2_fu_385_p3 );

    SC_METHOD(thread_tmp_17_fu_465_p2);
    sensitive << ( tmp_8_cast_fu_462_p1 );

    SC_METHOD(thread_tmp_18_fu_656_p3);
    sensitive << ( j_mid2_reg_1337 );

    SC_METHOD(thread_tmp_19_cast_fu_471_p1);
    sensitive << ( tmp_17_fu_465_p2 );

    SC_METHOD(thread_tmp_19_fu_807_p2);
    sensitive << ( tmp_8_cast5_fu_804_p1 );

    SC_METHOD(thread_tmp_1_fu_1094_p4);
    sensitive << ( tmp_2_mid2_v_v_v_reg_1289 );

    SC_METHOD(thread_tmp_20_fu_1110_p2);
    sensitive << ( tmp_2_cast_fu_1103_p1 );
    sensitive << ( tmp_8_cast6_fu_1107_p1 );

    SC_METHOD(thread_tmp_21_cast_fu_813_p1);
    sensitive << ( tmp_19_fu_807_p2 );

    SC_METHOD(thread_tmp_22_cast_fu_1116_p1);
    sensitive << ( tmp_20_fu_1110_p2 );

    SC_METHOD(thread_tmp_2_cast_fu_1103_p1);
    sensitive << ( tmp_1_fu_1094_p4 );

    SC_METHOD(thread_tmp_2_fu_338_p1);
    sensitive << ( tmp_3_fu_330_p3 );

    SC_METHOD(thread_tmp_2_mid2_v_v_v_fu_322_p3);
    sensitive << ( exitcond_fu_296_p2 );
    sensitive << ( i_reg_255 );
    sensitive << ( i_1_fu_290_p2 );

    SC_METHOD(thread_tmp_3_fu_330_p3);
    sensitive << ( tmp_2_mid2_v_v_v_fu_322_p3 );

    SC_METHOD(thread_tmp_5_fu_429_p2);
    sensitive << ( j_mid2_reg_1337 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_tmp_6_fu_591_p1);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( b_copy_0_3_11_fu_104 );
    sensitive << ( b_copy_0_3_15_fu_555_p3 );

    SC_METHOD(thread_tmp_6_fu_591_p2);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( b_copy_0_3_8_fu_108 );
    sensitive << ( b_copy_0_3_14_fu_547_p3 );

    SC_METHOD(thread_tmp_6_fu_591_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( b_copy_0_3_12_fu_112 );
    sensitive << ( b_copy_0_3_7_fu_531_p3 );

    SC_METHOD(thread_tmp_6_fu_591_p4);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( b_copy_0_3_1_fu_116 );
    sensitive << ( b_copy_0_3_2_fu_507_p3 );

    SC_METHOD(thread_tmp_7_fu_759_p1);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( b_copy_1_3_11_fu_120 );
    sensitive << ( b_copy_1_3_15_fu_720_p3 );

    SC_METHOD(thread_tmp_7_fu_759_p2);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( b_copy_1_3_8_fu_124 );
    sensitive << ( b_copy_1_3_14_fu_713_p3 );

    SC_METHOD(thread_tmp_7_fu_759_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( b_copy_1_3_12_fu_128 );
    sensitive << ( b_copy_1_3_7_fu_699_p3 );

    SC_METHOD(thread_tmp_7_fu_759_p4);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( b_copy_1_3_1_fu_132 );
    sensitive << ( b_copy_1_3_2_fu_678_p3 );

    SC_METHOD(thread_tmp_8_cast5_fu_804_p1);
    sensitive << ( j_mid2_reg_1337 );

    SC_METHOD(thread_tmp_8_cast6_fu_1107_p1);
    sensitive << ( j_mid2_reg_1337 );

    SC_METHOD(thread_tmp_8_cast_fu_462_p1);
    sensitive << ( j_mid2_reg_1337 );

    SC_METHOD(thread_tmp_8_fu_343_p2);
    sensitive << ( tmp_3_reg_1295 );

    SC_METHOD(thread_tmp_9_fu_913_p1);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( b_copy_2_3_11_fu_136 );
    sensitive << ( b_copy_2_3_15_fu_874_p3 );

    SC_METHOD(thread_tmp_9_fu_913_p2);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( b_copy_2_3_8_fu_140 );
    sensitive << ( b_copy_2_3_14_fu_867_p3 );

    SC_METHOD(thread_tmp_9_fu_913_p3);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( b_copy_2_3_12_fu_144 );
    sensitive << ( b_copy_2_3_7_fu_853_p3 );

    SC_METHOD(thread_tmp_9_fu_913_p4);
    sensitive << ( tmp_mid2_reg_1269 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( b_copy_2_3_1_fu_148 );
    sensitive << ( b_copy_2_3_2_fu_832_p3 );

    SC_METHOD(thread_tmp_fu_401_p1);
    sensitive << ( j_mid2_fu_385_p3 );

    SC_METHOD(thread_tmp_mid1_fu_302_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten_fu_278_p2 );
    sensitive << ( i_1_fu_290_p2 );

    SC_METHOD(thread_tmp_mid2_fu_314_p3);
    sensitive << ( exitcond_fu_296_p2 );
    sensitive << ( tmp_mid1_fu_302_p2 );
    sensitive << ( tmp1_fu_308_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_flatten_fu_278_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matmul_hw_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_Addr_A, "(port)a_Addr_A");
    sc_trace(mVcdFile, a_EN_A, "(port)a_EN_A");
    sc_trace(mVcdFile, a_WEN_A, "(port)a_WEN_A");
    sc_trace(mVcdFile, a_Din_A, "(port)a_Din_A");
    sc_trace(mVcdFile, a_Dout_A, "(port)a_Dout_A");
    sc_trace(mVcdFile, a_Clk_A, "(port)a_Clk_A");
    sc_trace(mVcdFile, a_Rst_A, "(port)a_Rst_A");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten_next_fu_284_p2, "indvar_flatten_next_fu_284_p2");
    sc_trace(mVcdFile, indvar_flatten_next_reg_1259, "indvar_flatten_next_reg_1259");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond_fu_296_p2, "exitcond_fu_296_p2");
    sc_trace(mVcdFile, exitcond_reg_1264, "exitcond_reg_1264");
    sc_trace(mVcdFile, exitcond_flatten_fu_278_p2, "exitcond_flatten_fu_278_p2");
    sc_trace(mVcdFile, tmp_mid2_fu_314_p3, "tmp_mid2_fu_314_p3");
    sc_trace(mVcdFile, tmp_mid2_reg_1269, "tmp_mid2_reg_1269");
    sc_trace(mVcdFile, tmp_2_mid2_v_v_v_fu_322_p3, "tmp_2_mid2_v_v_v_fu_322_p3");
    sc_trace(mVcdFile, tmp_2_mid2_v_v_v_reg_1289, "tmp_2_mid2_v_v_v_reg_1289");
    sc_trace(mVcdFile, tmp_3_fu_330_p3, "tmp_3_fu_330_p3");
    sc_trace(mVcdFile, tmp_3_reg_1295, "tmp_3_reg_1295");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, a_row_0_reg_1312, "a_row_0_reg_1312");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, a_row_1_reg_1322, "a_row_1_reg_1322");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, a_row_2_reg_1332, "a_row_2_reg_1332");
    sc_trace(mVcdFile, j_mid2_fu_385_p3, "j_mid2_fu_385_p3");
    sc_trace(mVcdFile, j_mid2_reg_1337, "j_mid2_reg_1337");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, a_row_3_reg_1347, "a_row_3_reg_1347");
    sc_trace(mVcdFile, tmp_fu_401_p1, "tmp_fu_401_p1");
    sc_trace(mVcdFile, tmp_reg_1357, "tmp_reg_1357");
    sc_trace(mVcdFile, a_row_3_1_fu_434_p3, "a_row_3_1_fu_434_p3");
    sc_trace(mVcdFile, a_row_3_1_reg_1368, "a_row_3_1_reg_1368");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, a_row_2_1_fu_441_p3, "a_row_2_1_fu_441_p3");
    sc_trace(mVcdFile, a_row_2_1_reg_1373, "a_row_2_1_reg_1373");
    sc_trace(mVcdFile, a_row_1_1_fu_448_p3, "a_row_1_1_fu_448_p3");
    sc_trace(mVcdFile, a_row_1_1_reg_1378, "a_row_1_1_reg_1378");
    sc_trace(mVcdFile, a_row_0_1_fu_455_p3, "a_row_0_1_fu_455_p3");
    sc_trace(mVcdFile, a_row_0_1_reg_1383, "a_row_0_1_reg_1383");
    sc_trace(mVcdFile, sel_tmp_fu_476_p2, "sel_tmp_fu_476_p2");
    sc_trace(mVcdFile, sel_tmp_reg_1393, "sel_tmp_reg_1393");
    sc_trace(mVcdFile, sel_tmp2_fu_489_p2, "sel_tmp2_fu_489_p2");
    sc_trace(mVcdFile, sel_tmp2_reg_1403, "sel_tmp2_reg_1403");
    sc_trace(mVcdFile, sel_tmp4_fu_502_p2, "sel_tmp4_fu_502_p2");
    sc_trace(mVcdFile, sel_tmp4_reg_1416, "sel_tmp4_reg_1416");
    sc_trace(mVcdFile, tmp_6_fu_591_p6, "tmp_6_fu_591_p6");
    sc_trace(mVcdFile, tmp_6_reg_1432, "tmp_6_reg_1432");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_7_fu_759_p6, "tmp_7_fu_759_p6");
    sc_trace(mVcdFile, tmp_7_reg_1442, "tmp_7_reg_1442");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_9_fu_913_p6, "tmp_9_fu_913_p6");
    sc_trace(mVcdFile, tmp_9_reg_1452, "tmp_9_reg_1452");
    sc_trace(mVcdFile, tmp_10_fu_1053_p6, "tmp_10_fu_1053_p6");
    sc_trace(mVcdFile, tmp_10_reg_1457, "tmp_10_reg_1457");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_755_p2, "grp_fu_755_p2");
    sc_trace(mVcdFile, tmp_s_reg_1462, "tmp_s_reg_1462");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, grp_fu_909_p2, "grp_fu_909_p2");
    sc_trace(mVcdFile, tmp_11_1_reg_1467, "tmp_11_1_reg_1467");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, grp_fu_1049_p2, "grp_fu_1049_p2");
    sc_trace(mVcdFile, tmp_11_2_reg_1472, "tmp_11_2_reg_1472");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, tmp2_fu_1090_p2, "tmp2_fu_1090_p2");
    sc_trace(mVcdFile, tmp2_reg_1477, "tmp2_reg_1477");
    sc_trace(mVcdFile, grp_fu_1086_p2, "grp_fu_1086_p2");
    sc_trace(mVcdFile, tmp_11_3_reg_1482, "tmp_11_3_reg_1482");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, j_1_fu_1131_p2, "j_1_fu_1131_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, indvar_flatten_reg_244, "indvar_flatten_reg_244");
    sc_trace(mVcdFile, i_reg_255, "i_reg_255");
    sc_trace(mVcdFile, j_reg_266, "j_reg_266");
    sc_trace(mVcdFile, tmp_2_fu_338_p1, "tmp_2_fu_338_p1");
    sc_trace(mVcdFile, tmp_11_fu_348_p3, "tmp_11_fu_348_p3");
    sc_trace(mVcdFile, tmp_13_fu_362_p3, "tmp_13_fu_362_p3");
    sc_trace(mVcdFile, tmp_15_fu_376_p3, "tmp_15_fu_376_p3");
    sc_trace(mVcdFile, tmp_16_fu_392_p3, "tmp_16_fu_392_p3");
    sc_trace(mVcdFile, tmp_19_cast_fu_471_p1, "tmp_19_cast_fu_471_p1");
    sc_trace(mVcdFile, tmp_18_fu_656_p3, "tmp_18_fu_656_p3");
    sc_trace(mVcdFile, tmp_21_cast_fu_813_p1, "tmp_21_cast_fu_813_p1");
    sc_trace(mVcdFile, tmp_22_cast_fu_1116_p1, "tmp_22_cast_fu_1116_p1");
    sc_trace(mVcdFile, a_row_0_2_fu_88, "a_row_0_2_fu_88");
    sc_trace(mVcdFile, a_row_1_2_fu_92, "a_row_1_2_fu_92");
    sc_trace(mVcdFile, a_row_2_2_fu_96, "a_row_2_2_fu_96");
    sc_trace(mVcdFile, a_row_3_2_fu_100, "a_row_3_2_fu_100");
    sc_trace(mVcdFile, b_copy_0_3_11_fu_104, "b_copy_0_3_11_fu_104");
    sc_trace(mVcdFile, b_copy_0_3_18_fu_584_p3, "b_copy_0_3_18_fu_584_p3");
    sc_trace(mVcdFile, b_copy_0_3_8_fu_108, "b_copy_0_3_8_fu_108");
    sc_trace(mVcdFile, b_copy_0_3_17_fu_577_p3, "b_copy_0_3_17_fu_577_p3");
    sc_trace(mVcdFile, b_copy_0_3_12_fu_112, "b_copy_0_3_12_fu_112");
    sc_trace(mVcdFile, b_copy_0_3_16_fu_570_p3, "b_copy_0_3_16_fu_570_p3");
    sc_trace(mVcdFile, b_copy_0_3_1_fu_116, "b_copy_0_3_1_fu_116");
    sc_trace(mVcdFile, b_copy_0_3_3_fu_563_p3, "b_copy_0_3_3_fu_563_p3");
    sc_trace(mVcdFile, b_copy_1_3_11_fu_120, "b_copy_1_3_11_fu_120");
    sc_trace(mVcdFile, b_copy_1_3_18_fu_748_p3, "b_copy_1_3_18_fu_748_p3");
    sc_trace(mVcdFile, b_copy_1_3_8_fu_124, "b_copy_1_3_8_fu_124");
    sc_trace(mVcdFile, b_copy_1_3_17_fu_741_p3, "b_copy_1_3_17_fu_741_p3");
    sc_trace(mVcdFile, b_copy_1_3_12_fu_128, "b_copy_1_3_12_fu_128");
    sc_trace(mVcdFile, b_copy_1_3_16_fu_734_p3, "b_copy_1_3_16_fu_734_p3");
    sc_trace(mVcdFile, b_copy_1_3_1_fu_132, "b_copy_1_3_1_fu_132");
    sc_trace(mVcdFile, b_copy_1_3_3_fu_727_p3, "b_copy_1_3_3_fu_727_p3");
    sc_trace(mVcdFile, b_copy_2_3_11_fu_136, "b_copy_2_3_11_fu_136");
    sc_trace(mVcdFile, b_copy_2_3_18_fu_902_p3, "b_copy_2_3_18_fu_902_p3");
    sc_trace(mVcdFile, b_copy_2_3_8_fu_140, "b_copy_2_3_8_fu_140");
    sc_trace(mVcdFile, b_copy_2_3_17_fu_895_p3, "b_copy_2_3_17_fu_895_p3");
    sc_trace(mVcdFile, b_copy_2_3_12_fu_144, "b_copy_2_3_12_fu_144");
    sc_trace(mVcdFile, b_copy_2_3_16_fu_888_p3, "b_copy_2_3_16_fu_888_p3");
    sc_trace(mVcdFile, b_copy_2_3_1_fu_148, "b_copy_2_3_1_fu_148");
    sc_trace(mVcdFile, b_copy_2_3_3_fu_881_p3, "b_copy_2_3_3_fu_881_p3");
    sc_trace(mVcdFile, b_copy_3_3_11_fu_152, "b_copy_3_3_11_fu_152");
    sc_trace(mVcdFile, b_copy_3_3_18_fu_1042_p3, "b_copy_3_3_18_fu_1042_p3");
    sc_trace(mVcdFile, b_copy_3_3_8_fu_156, "b_copy_3_3_8_fu_156");
    sc_trace(mVcdFile, b_copy_3_3_17_fu_1035_p3, "b_copy_3_3_17_fu_1035_p3");
    sc_trace(mVcdFile, b_copy_3_3_12_fu_160, "b_copy_3_3_12_fu_160");
    sc_trace(mVcdFile, b_copy_3_3_16_fu_1028_p3, "b_copy_3_3_16_fu_1028_p3");
    sc_trace(mVcdFile, b_copy_3_3_1_fu_164, "b_copy_3_3_1_fu_164");
    sc_trace(mVcdFile, b_copy_3_3_3_fu_1021_p3, "b_copy_3_3_3_fu_1021_p3");
    sc_trace(mVcdFile, a_Addr_A_orig, "a_Addr_A_orig");
    sc_trace(mVcdFile, i_1_fu_290_p2, "i_1_fu_290_p2");
    sc_trace(mVcdFile, tmp_mid1_fu_302_p2, "tmp_mid1_fu_302_p2");
    sc_trace(mVcdFile, tmp1_fu_308_p2, "tmp1_fu_308_p2");
    sc_trace(mVcdFile, tmp_8_fu_343_p2, "tmp_8_fu_343_p2");
    sc_trace(mVcdFile, tmp_12_fu_357_p2, "tmp_12_fu_357_p2");
    sc_trace(mVcdFile, tmp_14_fu_371_p2, "tmp_14_fu_371_p2");
    sc_trace(mVcdFile, tmp_5_fu_429_p2, "tmp_5_fu_429_p2");
    sc_trace(mVcdFile, tmp_8_cast_fu_462_p1, "tmp_8_cast_fu_462_p1");
    sc_trace(mVcdFile, tmp_17_fu_465_p2, "tmp_17_fu_465_p2");
    sc_trace(mVcdFile, b_copy_0_3_fu_481_p3, "b_copy_0_3_fu_481_p3");
    sc_trace(mVcdFile, b_copy_0_3_4_fu_494_p3, "b_copy_0_3_4_fu_494_p3");
    sc_trace(mVcdFile, b_copy_0_3_5_fu_515_p3, "b_copy_0_3_5_fu_515_p3");
    sc_trace(mVcdFile, b_copy_0_3_6_fu_523_p3, "b_copy_0_3_6_fu_523_p3");
    sc_trace(mVcdFile, b_copy_0_3_9_fu_539_p3, "b_copy_0_3_9_fu_539_p3");
    sc_trace(mVcdFile, b_copy_0_3_2_fu_507_p3, "b_copy_0_3_2_fu_507_p3");
    sc_trace(mVcdFile, b_copy_0_3_7_fu_531_p3, "b_copy_0_3_7_fu_531_p3");
    sc_trace(mVcdFile, b_copy_0_3_14_fu_547_p3, "b_copy_0_3_14_fu_547_p3");
    sc_trace(mVcdFile, b_copy_0_3_15_fu_555_p3, "b_copy_0_3_15_fu_555_p3");
    sc_trace(mVcdFile, tmp_6_fu_591_p1, "tmp_6_fu_591_p1");
    sc_trace(mVcdFile, tmp_6_fu_591_p2, "tmp_6_fu_591_p2");
    sc_trace(mVcdFile, tmp_6_fu_591_p3, "tmp_6_fu_591_p3");
    sc_trace(mVcdFile, tmp_6_fu_591_p4, "tmp_6_fu_591_p4");
    sc_trace(mVcdFile, b_copy_1_3_fu_664_p3, "b_copy_1_3_fu_664_p3");
    sc_trace(mVcdFile, b_copy_1_3_4_fu_671_p3, "b_copy_1_3_4_fu_671_p3");
    sc_trace(mVcdFile, b_copy_1_3_5_fu_685_p3, "b_copy_1_3_5_fu_685_p3");
    sc_trace(mVcdFile, b_copy_1_3_6_fu_692_p3, "b_copy_1_3_6_fu_692_p3");
    sc_trace(mVcdFile, b_copy_1_3_9_fu_706_p3, "b_copy_1_3_9_fu_706_p3");
    sc_trace(mVcdFile, b_copy_1_3_2_fu_678_p3, "b_copy_1_3_2_fu_678_p3");
    sc_trace(mVcdFile, b_copy_1_3_7_fu_699_p3, "b_copy_1_3_7_fu_699_p3");
    sc_trace(mVcdFile, b_copy_1_3_14_fu_713_p3, "b_copy_1_3_14_fu_713_p3");
    sc_trace(mVcdFile, b_copy_1_3_15_fu_720_p3, "b_copy_1_3_15_fu_720_p3");
    sc_trace(mVcdFile, tmp_7_fu_759_p1, "tmp_7_fu_759_p1");
    sc_trace(mVcdFile, tmp_7_fu_759_p2, "tmp_7_fu_759_p2");
    sc_trace(mVcdFile, tmp_7_fu_759_p3, "tmp_7_fu_759_p3");
    sc_trace(mVcdFile, tmp_7_fu_759_p4, "tmp_7_fu_759_p4");
    sc_trace(mVcdFile, tmp_8_cast5_fu_804_p1, "tmp_8_cast5_fu_804_p1");
    sc_trace(mVcdFile, tmp_19_fu_807_p2, "tmp_19_fu_807_p2");
    sc_trace(mVcdFile, b_copy_2_3_fu_818_p3, "b_copy_2_3_fu_818_p3");
    sc_trace(mVcdFile, b_copy_2_3_4_fu_825_p3, "b_copy_2_3_4_fu_825_p3");
    sc_trace(mVcdFile, b_copy_2_3_5_fu_839_p3, "b_copy_2_3_5_fu_839_p3");
    sc_trace(mVcdFile, b_copy_2_3_6_fu_846_p3, "b_copy_2_3_6_fu_846_p3");
    sc_trace(mVcdFile, b_copy_2_3_9_fu_860_p3, "b_copy_2_3_9_fu_860_p3");
    sc_trace(mVcdFile, b_copy_2_3_2_fu_832_p3, "b_copy_2_3_2_fu_832_p3");
    sc_trace(mVcdFile, b_copy_2_3_7_fu_853_p3, "b_copy_2_3_7_fu_853_p3");
    sc_trace(mVcdFile, b_copy_2_3_14_fu_867_p3, "b_copy_2_3_14_fu_867_p3");
    sc_trace(mVcdFile, b_copy_2_3_15_fu_874_p3, "b_copy_2_3_15_fu_874_p3");
    sc_trace(mVcdFile, tmp_9_fu_913_p1, "tmp_9_fu_913_p1");
    sc_trace(mVcdFile, tmp_9_fu_913_p2, "tmp_9_fu_913_p2");
    sc_trace(mVcdFile, tmp_9_fu_913_p3, "tmp_9_fu_913_p3");
    sc_trace(mVcdFile, tmp_9_fu_913_p4, "tmp_9_fu_913_p4");
    sc_trace(mVcdFile, b_copy_3_3_fu_958_p3, "b_copy_3_3_fu_958_p3");
    sc_trace(mVcdFile, b_copy_3_3_4_fu_965_p3, "b_copy_3_3_4_fu_965_p3");
    sc_trace(mVcdFile, b_copy_3_3_5_fu_979_p3, "b_copy_3_3_5_fu_979_p3");
    sc_trace(mVcdFile, b_copy_3_3_6_fu_986_p3, "b_copy_3_3_6_fu_986_p3");
    sc_trace(mVcdFile, b_copy_3_3_9_fu_1000_p3, "b_copy_3_3_9_fu_1000_p3");
    sc_trace(mVcdFile, b_copy_3_3_2_fu_972_p3, "b_copy_3_3_2_fu_972_p3");
    sc_trace(mVcdFile, b_copy_3_3_7_fu_993_p3, "b_copy_3_3_7_fu_993_p3");
    sc_trace(mVcdFile, b_copy_3_3_14_fu_1007_p3, "b_copy_3_3_14_fu_1007_p3");
    sc_trace(mVcdFile, b_copy_3_3_15_fu_1014_p3, "b_copy_3_3_15_fu_1014_p3");
    sc_trace(mVcdFile, tmp_10_fu_1053_p1, "tmp_10_fu_1053_p1");
    sc_trace(mVcdFile, tmp_10_fu_1053_p2, "tmp_10_fu_1053_p2");
    sc_trace(mVcdFile, tmp_10_fu_1053_p3, "tmp_10_fu_1053_p3");
    sc_trace(mVcdFile, tmp_10_fu_1053_p4, "tmp_10_fu_1053_p4");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, tmp_1_fu_1094_p4, "tmp_1_fu_1094_p4");
    sc_trace(mVcdFile, tmp_2_cast_fu_1103_p1, "tmp_2_cast_fu_1103_p1");
    sc_trace(mVcdFile, tmp_8_cast6_fu_1107_p1, "tmp_8_cast6_fu_1107_p1");
    sc_trace(mVcdFile, tmp_20_fu_1110_p2, "tmp_20_fu_1110_p2");
    sc_trace(mVcdFile, tmp3_fu_1121_p2, "tmp3_fu_1121_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("matmul_hw.hdltvin.dat");
    mHdltvoutHandle.open("matmul_hw.hdltvout.dat");
}

matmul_hw::~matmul_hw() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete matmul_hw_mux_42_bkb_U1;
    delete matmul_hw_mul_32scud_U2;
    delete matmul_hw_mux_42_bkb_U3;
    delete matmul_hw_mul_32scud_U4;
    delete matmul_hw_mux_42_bkb_U5;
    delete matmul_hw_mul_32scud_U6;
    delete matmul_hw_mux_42_bkb_U7;
    delete matmul_hw_mul_32scud_U8;
}

void matmul_hw::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void matmul_hw::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read()))) {
        i_reg_255 = tmp_2_mid2_v_v_v_reg_1289.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_255 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read()))) {
        indvar_flatten_reg_244 = indvar_flatten_next_reg_1259.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten_reg_244 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read()))) {
        j_reg_266 = j_1_fu_1131_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        j_reg_266 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()))) {
        a_row_0_1_reg_1383 = a_row_0_1_fu_455_p3.read();
        a_row_0_2_fu_88 = a_row_0_1_fu_455_p3.read();
        a_row_1_1_reg_1378 = a_row_1_1_fu_448_p3.read();
        a_row_1_2_fu_92 = a_row_1_1_fu_448_p3.read();
        a_row_2_1_reg_1373 = a_row_2_1_fu_441_p3.read();
        a_row_2_2_fu_96 = a_row_2_1_fu_441_p3.read();
        a_row_3_1_reg_1368 = a_row_3_1_fu_434_p3.read();
        a_row_3_2_fu_100 = a_row_3_1_fu_434_p3.read();
        b_copy_0_3_11_fu_104 = b_copy_0_3_18_fu_584_p3.read();
        b_copy_0_3_12_fu_112 = b_copy_0_3_16_fu_570_p3.read();
        b_copy_0_3_1_fu_116 = b_copy_0_3_3_fu_563_p3.read();
        b_copy_0_3_8_fu_108 = b_copy_0_3_17_fu_577_p3.read();
        sel_tmp2_reg_1403 = sel_tmp2_fu_489_p2.read();
        sel_tmp4_reg_1416 = sel_tmp4_fu_502_p2.read();
        sel_tmp_reg_1393 = sel_tmp_fu_476_p2.read();
        tmp_6_reg_1432 = tmp_6_fu_591_p6.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        a_row_0_reg_1312 = a_Dout_A.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        a_row_1_reg_1322 = a_Dout_A.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()))) {
        a_row_2_reg_1332 = a_Dout_A.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        a_row_3_reg_1347 = a_Dout_A.read();
        j_mid2_reg_1337 = j_mid2_fu_385_p3.read();
        tmp_reg_1357 = tmp_fu_401_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        b_copy_1_3_11_fu_120 = b_copy_1_3_18_fu_748_p3.read();
        b_copy_1_3_12_fu_128 = b_copy_1_3_16_fu_734_p3.read();
        b_copy_1_3_1_fu_132 = b_copy_1_3_3_fu_727_p3.read();
        b_copy_1_3_8_fu_124 = b_copy_1_3_17_fu_741_p3.read();
        tmp_7_reg_1442 = tmp_7_fu_759_p6.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()))) {
        b_copy_2_3_11_fu_136 = b_copy_2_3_18_fu_902_p3.read();
        b_copy_2_3_12_fu_144 = b_copy_2_3_16_fu_888_p3.read();
        b_copy_2_3_1_fu_148 = b_copy_2_3_3_fu_881_p3.read();
        b_copy_2_3_8_fu_140 = b_copy_2_3_17_fu_895_p3.read();
        tmp_9_reg_1452 = tmp_9_fu_913_p6.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()))) {
        b_copy_3_3_11_fu_152 = b_copy_3_3_18_fu_1042_p3.read();
        b_copy_3_3_12_fu_160 = b_copy_3_3_16_fu_1028_p3.read();
        b_copy_3_3_1_fu_164 = b_copy_3_3_3_fu_1021_p3.read();
        b_copy_3_3_8_fu_156 = b_copy_3_3_17_fu_1035_p3.read();
        tmp_10_reg_1457 = tmp_10_fu_1053_p6.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_278_p2.read(), ap_const_lv1_0))) {
        exitcond_reg_1264 = exitcond_fu_296_p2.read();
        tmp_2_mid2_v_v_v_reg_1289 = tmp_2_mid2_v_v_v_fu_322_p3.read();
        tmp_3_reg_1295 = tmp_3_fu_330_p3.read();
        tmp_mid2_reg_1269 = tmp_mid2_fu_314_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        indvar_flatten_next_reg_1259 = indvar_flatten_next_fu_284_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read()))) {
        tmp2_reg_1477 = tmp2_fu_1090_p2.read();
        tmp_11_2_reg_1472 = grp_fu_1049_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()))) {
        tmp_11_1_reg_1467 = grp_fu_909_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()))) {
        tmp_11_3_reg_1482 = grp_fu_1086_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        tmp_s_reg_1462 = grp_fu_755_p2.read();
    }
}

void matmul_hw::thread_a_Addr_A() {
    a_Addr_A = (!ap_const_lv32_2.is_01())? sc_lv<32>(): a_Addr_A_orig.read() << (unsigned short)ap_const_lv32_2.to_uint();
}

void matmul_hw::thread_a_Addr_A_orig() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read()))) {
        a_Addr_A_orig =  (sc_lv<32>) (tmp_22_cast_fu_1116_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()))) {
        a_Addr_A_orig =  (sc_lv<32>) (tmp_21_cast_fu_813_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        a_Addr_A_orig =  (sc_lv<32>) (tmp_18_fu_656_p3.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()))) {
        a_Addr_A_orig =  (sc_lv<32>) (tmp_19_cast_fu_471_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        a_Addr_A_orig =  (sc_lv<32>) (tmp_16_fu_392_p3.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()))) {
        a_Addr_A_orig =  (sc_lv<32>) (tmp_15_fu_376_p3.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        a_Addr_A_orig =  (sc_lv<32>) (tmp_13_fu_362_p3.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        a_Addr_A_orig =  (sc_lv<32>) (tmp_11_fu_348_p3.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        a_Addr_A_orig =  (sc_lv<32>) (tmp_2_fu_338_p1.read());
    } else {
        a_Addr_A_orig = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void matmul_hw::thread_a_Clk_A() {
    a_Clk_A = ap_clk.read()? SC_LOGIC_1 : SC_LOGIC_0;
}

void matmul_hw::thread_a_Din_A() {
    a_Din_A = (!tmp2_reg_1477.read().is_01() || !tmp3_fu_1121_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp2_reg_1477.read()) + sc_biguint<32>(tmp3_fu_1121_p2.read()));
}

void matmul_hw::thread_a_EN_A() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read())))) {
        a_EN_A = ap_const_logic_1;
    } else {
        a_EN_A = ap_const_logic_0;
    }
}

void matmul_hw::thread_a_Rst_A() {
    a_Rst_A = ap_rst.read();
}

void matmul_hw::thread_a_WEN_A() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read())))) {
        a_WEN_A = ap_const_lv4_F;
    } else {
        a_WEN_A = ap_const_lv4_0;
    }
}

void matmul_hw::thread_a_row_0_1_fu_455_p3() {
    a_row_0_1_fu_455_p3 = (!tmp_5_fu_429_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_5_fu_429_p2.read()[0].to_bool())? a_row_0_reg_1312.read(): a_row_0_2_fu_88.read());
}

void matmul_hw::thread_a_row_1_1_fu_448_p3() {
    a_row_1_1_fu_448_p3 = (!tmp_5_fu_429_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_5_fu_429_p2.read()[0].to_bool())? a_row_1_reg_1322.read(): a_row_1_2_fu_92.read());
}

void matmul_hw::thread_a_row_2_1_fu_441_p3() {
    a_row_2_1_fu_441_p3 = (!tmp_5_fu_429_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_5_fu_429_p2.read()[0].to_bool())? a_row_2_reg_1332.read(): a_row_2_2_fu_96.read());
}

void matmul_hw::thread_a_row_3_1_fu_434_p3() {
    a_row_3_1_fu_434_p3 = (!tmp_5_fu_429_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_5_fu_429_p2.read()[0].to_bool())? a_row_3_reg_1347.read(): a_row_3_2_fu_100.read());
}

void matmul_hw::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void matmul_hw::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read().range(9, 9);
}

void matmul_hw::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read().range(10, 10);
}

void matmul_hw::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read().range(12, 12);
}

void matmul_hw::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read().range(13, 13);
}

void matmul_hw::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read().range(14, 14);
}

void matmul_hw::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read().range(15, 15);
}

void matmul_hw::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read().range(16, 16);
}

void matmul_hw::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read().range(17, 17);
}

void matmul_hw::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void matmul_hw::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read().range(2, 2);
}

void matmul_hw::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read().range(3, 3);
}

void matmul_hw::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read().range(4, 4);
}

void matmul_hw::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read().range(5, 5);
}

void matmul_hw::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read().range(6, 6);
}

void matmul_hw::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read().range(7, 7);
}

void matmul_hw::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read().range(8, 8);
}

void matmul_hw::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matmul_hw::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matmul_hw::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matmul_hw::thread_b_copy_0_3_14_fu_547_p3() {
    b_copy_0_3_14_fu_547_p3 = (!sel_tmp4_fu_502_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_fu_502_p2.read()[0].to_bool())? b_copy_0_3_8_fu_108.read(): b_copy_0_3_9_fu_539_p3.read());
}

void matmul_hw::thread_b_copy_0_3_15_fu_555_p3() {
    b_copy_0_3_15_fu_555_p3 = (!sel_tmp4_fu_502_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_fu_502_p2.read()[0].to_bool())? a_Dout_A.read(): b_copy_0_3_11_fu_104.read());
}

void matmul_hw::thread_b_copy_0_3_16_fu_570_p3() {
    b_copy_0_3_16_fu_570_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_0_3_7_fu_531_p3.read(): b_copy_0_3_12_fu_112.read());
}

void matmul_hw::thread_b_copy_0_3_17_fu_577_p3() {
    b_copy_0_3_17_fu_577_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_0_3_14_fu_547_p3.read(): b_copy_0_3_8_fu_108.read());
}

void matmul_hw::thread_b_copy_0_3_18_fu_584_p3() {
    b_copy_0_3_18_fu_584_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_0_3_15_fu_555_p3.read(): b_copy_0_3_11_fu_104.read());
}

void matmul_hw::thread_b_copy_0_3_2_fu_507_p3() {
    b_copy_0_3_2_fu_507_p3 = (!sel_tmp4_fu_502_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_fu_502_p2.read()[0].to_bool())? b_copy_0_3_1_fu_116.read(): b_copy_0_3_4_fu_494_p3.read());
}

void matmul_hw::thread_b_copy_0_3_3_fu_563_p3() {
    b_copy_0_3_3_fu_563_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_0_3_2_fu_507_p3.read(): b_copy_0_3_1_fu_116.read());
}

void matmul_hw::thread_b_copy_0_3_4_fu_494_p3() {
    b_copy_0_3_4_fu_494_p3 = (!sel_tmp2_fu_489_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_fu_489_p2.read()[0].to_bool())? b_copy_0_3_1_fu_116.read(): b_copy_0_3_fu_481_p3.read());
}

void matmul_hw::thread_b_copy_0_3_5_fu_515_p3() {
    b_copy_0_3_5_fu_515_p3 = (!sel_tmp_fu_476_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_fu_476_p2.read()[0].to_bool())? a_Dout_A.read(): b_copy_0_3_12_fu_112.read());
}

void matmul_hw::thread_b_copy_0_3_6_fu_523_p3() {
    b_copy_0_3_6_fu_523_p3 = (!sel_tmp2_fu_489_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_fu_489_p2.read()[0].to_bool())? b_copy_0_3_12_fu_112.read(): b_copy_0_3_5_fu_515_p3.read());
}

void matmul_hw::thread_b_copy_0_3_7_fu_531_p3() {
    b_copy_0_3_7_fu_531_p3 = (!sel_tmp4_fu_502_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_fu_502_p2.read()[0].to_bool())? b_copy_0_3_12_fu_112.read(): b_copy_0_3_6_fu_523_p3.read());
}

void matmul_hw::thread_b_copy_0_3_9_fu_539_p3() {
    b_copy_0_3_9_fu_539_p3 = (!sel_tmp2_fu_489_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_fu_489_p2.read()[0].to_bool())? a_Dout_A.read(): b_copy_0_3_8_fu_108.read());
}

void matmul_hw::thread_b_copy_0_3_fu_481_p3() {
    b_copy_0_3_fu_481_p3 = (!sel_tmp_fu_476_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_fu_476_p2.read()[0].to_bool())? b_copy_0_3_1_fu_116.read(): a_Dout_A.read());
}

void matmul_hw::thread_b_copy_1_3_14_fu_713_p3() {
    b_copy_1_3_14_fu_713_p3 = (!sel_tmp4_reg_1416.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1416.read()[0].to_bool())? b_copy_1_3_8_fu_124.read(): b_copy_1_3_9_fu_706_p3.read());
}

void matmul_hw::thread_b_copy_1_3_15_fu_720_p3() {
    b_copy_1_3_15_fu_720_p3 = (!sel_tmp4_reg_1416.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1416.read()[0].to_bool())? a_Dout_A.read(): b_copy_1_3_11_fu_120.read());
}

void matmul_hw::thread_b_copy_1_3_16_fu_734_p3() {
    b_copy_1_3_16_fu_734_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_1_3_7_fu_699_p3.read(): b_copy_1_3_12_fu_128.read());
}

void matmul_hw::thread_b_copy_1_3_17_fu_741_p3() {
    b_copy_1_3_17_fu_741_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_1_3_14_fu_713_p3.read(): b_copy_1_3_8_fu_124.read());
}

void matmul_hw::thread_b_copy_1_3_18_fu_748_p3() {
    b_copy_1_3_18_fu_748_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_1_3_15_fu_720_p3.read(): b_copy_1_3_11_fu_120.read());
}

void matmul_hw::thread_b_copy_1_3_2_fu_678_p3() {
    b_copy_1_3_2_fu_678_p3 = (!sel_tmp4_reg_1416.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1416.read()[0].to_bool())? b_copy_1_3_1_fu_132.read(): b_copy_1_3_4_fu_671_p3.read());
}

void matmul_hw::thread_b_copy_1_3_3_fu_727_p3() {
    b_copy_1_3_3_fu_727_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_1_3_2_fu_678_p3.read(): b_copy_1_3_1_fu_132.read());
}

void matmul_hw::thread_b_copy_1_3_4_fu_671_p3() {
    b_copy_1_3_4_fu_671_p3 = (!sel_tmp2_reg_1403.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_reg_1403.read()[0].to_bool())? b_copy_1_3_1_fu_132.read(): b_copy_1_3_fu_664_p3.read());
}

void matmul_hw::thread_b_copy_1_3_5_fu_685_p3() {
    b_copy_1_3_5_fu_685_p3 = (!sel_tmp_reg_1393.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_reg_1393.read()[0].to_bool())? a_Dout_A.read(): b_copy_1_3_12_fu_128.read());
}

void matmul_hw::thread_b_copy_1_3_6_fu_692_p3() {
    b_copy_1_3_6_fu_692_p3 = (!sel_tmp2_reg_1403.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_reg_1403.read()[0].to_bool())? b_copy_1_3_12_fu_128.read(): b_copy_1_3_5_fu_685_p3.read());
}

void matmul_hw::thread_b_copy_1_3_7_fu_699_p3() {
    b_copy_1_3_7_fu_699_p3 = (!sel_tmp4_reg_1416.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1416.read()[0].to_bool())? b_copy_1_3_12_fu_128.read(): b_copy_1_3_6_fu_692_p3.read());
}

void matmul_hw::thread_b_copy_1_3_9_fu_706_p3() {
    b_copy_1_3_9_fu_706_p3 = (!sel_tmp2_reg_1403.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_reg_1403.read()[0].to_bool())? a_Dout_A.read(): b_copy_1_3_8_fu_124.read());
}

void matmul_hw::thread_b_copy_1_3_fu_664_p3() {
    b_copy_1_3_fu_664_p3 = (!sel_tmp_reg_1393.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_reg_1393.read()[0].to_bool())? b_copy_1_3_1_fu_132.read(): a_Dout_A.read());
}

void matmul_hw::thread_b_copy_2_3_14_fu_867_p3() {
    b_copy_2_3_14_fu_867_p3 = (!sel_tmp4_reg_1416.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1416.read()[0].to_bool())? b_copy_2_3_8_fu_140.read(): b_copy_2_3_9_fu_860_p3.read());
}

void matmul_hw::thread_b_copy_2_3_15_fu_874_p3() {
    b_copy_2_3_15_fu_874_p3 = (!sel_tmp4_reg_1416.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1416.read()[0].to_bool())? a_Dout_A.read(): b_copy_2_3_11_fu_136.read());
}

void matmul_hw::thread_b_copy_2_3_16_fu_888_p3() {
    b_copy_2_3_16_fu_888_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_2_3_7_fu_853_p3.read(): b_copy_2_3_12_fu_144.read());
}

void matmul_hw::thread_b_copy_2_3_17_fu_895_p3() {
    b_copy_2_3_17_fu_895_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_2_3_14_fu_867_p3.read(): b_copy_2_3_8_fu_140.read());
}

void matmul_hw::thread_b_copy_2_3_18_fu_902_p3() {
    b_copy_2_3_18_fu_902_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_2_3_15_fu_874_p3.read(): b_copy_2_3_11_fu_136.read());
}

void matmul_hw::thread_b_copy_2_3_2_fu_832_p3() {
    b_copy_2_3_2_fu_832_p3 = (!sel_tmp4_reg_1416.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1416.read()[0].to_bool())? b_copy_2_3_1_fu_148.read(): b_copy_2_3_4_fu_825_p3.read());
}

void matmul_hw::thread_b_copy_2_3_3_fu_881_p3() {
    b_copy_2_3_3_fu_881_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_2_3_2_fu_832_p3.read(): b_copy_2_3_1_fu_148.read());
}

void matmul_hw::thread_b_copy_2_3_4_fu_825_p3() {
    b_copy_2_3_4_fu_825_p3 = (!sel_tmp2_reg_1403.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_reg_1403.read()[0].to_bool())? b_copy_2_3_1_fu_148.read(): b_copy_2_3_fu_818_p3.read());
}

void matmul_hw::thread_b_copy_2_3_5_fu_839_p3() {
    b_copy_2_3_5_fu_839_p3 = (!sel_tmp_reg_1393.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_reg_1393.read()[0].to_bool())? a_Dout_A.read(): b_copy_2_3_12_fu_144.read());
}

void matmul_hw::thread_b_copy_2_3_6_fu_846_p3() {
    b_copy_2_3_6_fu_846_p3 = (!sel_tmp2_reg_1403.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_reg_1403.read()[0].to_bool())? b_copy_2_3_12_fu_144.read(): b_copy_2_3_5_fu_839_p3.read());
}

void matmul_hw::thread_b_copy_2_3_7_fu_853_p3() {
    b_copy_2_3_7_fu_853_p3 = (!sel_tmp4_reg_1416.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1416.read()[0].to_bool())? b_copy_2_3_12_fu_144.read(): b_copy_2_3_6_fu_846_p3.read());
}

void matmul_hw::thread_b_copy_2_3_9_fu_860_p3() {
    b_copy_2_3_9_fu_860_p3 = (!sel_tmp2_reg_1403.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_reg_1403.read()[0].to_bool())? a_Dout_A.read(): b_copy_2_3_8_fu_140.read());
}

void matmul_hw::thread_b_copy_2_3_fu_818_p3() {
    b_copy_2_3_fu_818_p3 = (!sel_tmp_reg_1393.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_reg_1393.read()[0].to_bool())? b_copy_2_3_1_fu_148.read(): a_Dout_A.read());
}

void matmul_hw::thread_b_copy_3_3_14_fu_1007_p3() {
    b_copy_3_3_14_fu_1007_p3 = (!sel_tmp4_reg_1416.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1416.read()[0].to_bool())? b_copy_3_3_8_fu_156.read(): b_copy_3_3_9_fu_1000_p3.read());
}

void matmul_hw::thread_b_copy_3_3_15_fu_1014_p3() {
    b_copy_3_3_15_fu_1014_p3 = (!sel_tmp4_reg_1416.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1416.read()[0].to_bool())? a_Dout_A.read(): b_copy_3_3_11_fu_152.read());
}

void matmul_hw::thread_b_copy_3_3_16_fu_1028_p3() {
    b_copy_3_3_16_fu_1028_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_3_3_7_fu_993_p3.read(): b_copy_3_3_12_fu_160.read());
}

void matmul_hw::thread_b_copy_3_3_17_fu_1035_p3() {
    b_copy_3_3_17_fu_1035_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_3_3_14_fu_1007_p3.read(): b_copy_3_3_8_fu_156.read());
}

void matmul_hw::thread_b_copy_3_3_18_fu_1042_p3() {
    b_copy_3_3_18_fu_1042_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_3_3_15_fu_1014_p3.read(): b_copy_3_3_11_fu_152.read());
}

void matmul_hw::thread_b_copy_3_3_2_fu_972_p3() {
    b_copy_3_3_2_fu_972_p3 = (!sel_tmp4_reg_1416.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1416.read()[0].to_bool())? b_copy_3_3_1_fu_164.read(): b_copy_3_3_4_fu_965_p3.read());
}

void matmul_hw::thread_b_copy_3_3_3_fu_1021_p3() {
    b_copy_3_3_3_fu_1021_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_3_3_2_fu_972_p3.read(): b_copy_3_3_1_fu_164.read());
}

void matmul_hw::thread_b_copy_3_3_4_fu_965_p3() {
    b_copy_3_3_4_fu_965_p3 = (!sel_tmp2_reg_1403.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_reg_1403.read()[0].to_bool())? b_copy_3_3_1_fu_164.read(): b_copy_3_3_fu_958_p3.read());
}

void matmul_hw::thread_b_copy_3_3_5_fu_979_p3() {
    b_copy_3_3_5_fu_979_p3 = (!sel_tmp_reg_1393.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_reg_1393.read()[0].to_bool())? a_Dout_A.read(): b_copy_3_3_12_fu_160.read());
}

void matmul_hw::thread_b_copy_3_3_6_fu_986_p3() {
    b_copy_3_3_6_fu_986_p3 = (!sel_tmp2_reg_1403.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_reg_1403.read()[0].to_bool())? b_copy_3_3_12_fu_160.read(): b_copy_3_3_5_fu_979_p3.read());
}

void matmul_hw::thread_b_copy_3_3_7_fu_993_p3() {
    b_copy_3_3_7_fu_993_p3 = (!sel_tmp4_reg_1416.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1416.read()[0].to_bool())? b_copy_3_3_12_fu_160.read(): b_copy_3_3_6_fu_986_p3.read());
}

void matmul_hw::thread_b_copy_3_3_9_fu_1000_p3() {
    b_copy_3_3_9_fu_1000_p3 = (!sel_tmp2_reg_1403.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_reg_1403.read()[0].to_bool())? a_Dout_A.read(): b_copy_3_3_8_fu_156.read());
}

void matmul_hw::thread_b_copy_3_3_fu_958_p3() {
    b_copy_3_3_fu_958_p3 = (!sel_tmp_reg_1393.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_reg_1393.read()[0].to_bool())? b_copy_3_3_1_fu_164.read(): a_Dout_A.read());
}

void matmul_hw::thread_exitcond_flatten_fu_278_p2() {
    exitcond_flatten_fu_278_p2 = (!indvar_flatten_reg_244.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_244.read() == ap_const_lv5_10);
}

void matmul_hw::thread_exitcond_fu_296_p2() {
    exitcond_fu_296_p2 = (!j_reg_266.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_266.read() == ap_const_lv3_4);
}

void matmul_hw::thread_i_1_fu_290_p2() {
    i_1_fu_290_p2 = (!ap_const_lv3_1.is_01() || !i_reg_255.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(i_reg_255.read()));
}

void matmul_hw::thread_indvar_flatten_next_fu_284_p2() {
    indvar_flatten_next_fu_284_p2 = (!indvar_flatten_reg_244.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(indvar_flatten_reg_244.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void matmul_hw::thread_j_1_fu_1131_p2() {
    j_1_fu_1131_p2 = (!ap_const_lv3_1.is_01() || !j_mid2_reg_1337.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(j_mid2_reg_1337.read()));
}

void matmul_hw::thread_j_mid2_fu_385_p3() {
    j_mid2_fu_385_p3 = (!exitcond_reg_1264.read()[0].is_01())? sc_lv<3>(): ((exitcond_reg_1264.read()[0].to_bool())? ap_const_lv3_0: j_reg_266.read());
}

void matmul_hw::thread_sel_tmp2_fu_489_p2() {
    sel_tmp2_fu_489_p2 = (!tmp_reg_1357.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_reg_1357.read() == ap_const_lv2_1);
}

void matmul_hw::thread_sel_tmp4_fu_502_p2() {
    sel_tmp4_fu_502_p2 = (!tmp_reg_1357.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_reg_1357.read() == ap_const_lv2_0);
}

void matmul_hw::thread_sel_tmp_fu_476_p2() {
    sel_tmp_fu_476_p2 = (!tmp_reg_1357.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(tmp_reg_1357.read() == ap_const_lv2_2);
}

void matmul_hw::thread_tmp1_fu_308_p2() {
    tmp1_fu_308_p2 = (!i_reg_255.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_255.read() == ap_const_lv3_0);
}

void matmul_hw::thread_tmp2_fu_1090_p2() {
    tmp2_fu_1090_p2 = (!tmp_11_1_reg_1467.read().is_01() || !tmp_s_reg_1462.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_11_1_reg_1467.read()) + sc_biguint<32>(tmp_s_reg_1462.read()));
}

void matmul_hw::thread_tmp3_fu_1121_p2() {
    tmp3_fu_1121_p2 = (!tmp_11_3_reg_1482.read().is_01() || !tmp_11_2_reg_1472.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_11_3_reg_1482.read()) + sc_biguint<32>(tmp_11_2_reg_1472.read()));
}

void matmul_hw::thread_tmp_10_fu_1053_p1() {
    tmp_10_fu_1053_p1 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_3_3_15_fu_1014_p3.read(): b_copy_3_3_11_fu_152.read());
}

void matmul_hw::thread_tmp_10_fu_1053_p2() {
    tmp_10_fu_1053_p2 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_3_3_14_fu_1007_p3.read(): b_copy_3_3_8_fu_156.read());
}

void matmul_hw::thread_tmp_10_fu_1053_p3() {
    tmp_10_fu_1053_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_3_3_7_fu_993_p3.read(): b_copy_3_3_12_fu_160.read());
}

void matmul_hw::thread_tmp_10_fu_1053_p4() {
    tmp_10_fu_1053_p4 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_3_3_2_fu_972_p3.read(): b_copy_3_3_1_fu_164.read());
}

void matmul_hw::thread_tmp_11_fu_348_p3() {
    tmp_11_fu_348_p3 = esl_concat<59,5>(ap_const_lv59_0, tmp_8_fu_343_p2.read());
}

void matmul_hw::thread_tmp_12_fu_357_p2() {
    tmp_12_fu_357_p2 = (tmp_3_reg_1295.read() | ap_const_lv5_2);
}

void matmul_hw::thread_tmp_13_fu_362_p3() {
    tmp_13_fu_362_p3 = esl_concat<59,5>(ap_const_lv59_0, tmp_12_fu_357_p2.read());
}

void matmul_hw::thread_tmp_14_fu_371_p2() {
    tmp_14_fu_371_p2 = (tmp_3_reg_1295.read() | ap_const_lv5_3);
}

void matmul_hw::thread_tmp_15_fu_376_p3() {
    tmp_15_fu_376_p3 = esl_concat<59,5>(ap_const_lv59_0, tmp_14_fu_371_p2.read());
}

void matmul_hw::thread_tmp_16_fu_392_p3() {
    tmp_16_fu_392_p3 = esl_concat<61,3>(ap_const_lv61_2, j_mid2_fu_385_p3.read());
}

void matmul_hw::thread_tmp_17_fu_465_p2() {
    tmp_17_fu_465_p2 = (!ap_const_lv5_14.is_01() || !tmp_8_cast_fu_462_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(ap_const_lv5_14) + sc_biguint<5>(tmp_8_cast_fu_462_p1.read()));
}

void matmul_hw::thread_tmp_18_fu_656_p3() {
    tmp_18_fu_656_p3 = esl_concat<61,3>(ap_const_lv61_3, j_mid2_reg_1337.read());
}

void matmul_hw::thread_tmp_19_cast_fu_471_p1() {
    tmp_19_cast_fu_471_p1 = esl_zext<64,5>(tmp_17_fu_465_p2.read());
}

void matmul_hw::thread_tmp_19_fu_807_p2() {
    tmp_19_fu_807_p2 = (!ap_const_lv6_1C.is_01() || !tmp_8_cast5_fu_804_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1C) + sc_biguint<6>(tmp_8_cast5_fu_804_p1.read()));
}

void matmul_hw::thread_tmp_1_fu_1094_p4() {
    tmp_1_fu_1094_p4 = esl_concat<4,2>(esl_concat<1,3>(ap_const_lv1_1, tmp_2_mid2_v_v_v_reg_1289.read()), ap_const_lv2_0);
}

void matmul_hw::thread_tmp_20_fu_1110_p2() {
    tmp_20_fu_1110_p2 = (!tmp_2_cast_fu_1103_p1.read().is_01() || !tmp_8_cast6_fu_1107_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_2_cast_fu_1103_p1.read()) + sc_biguint<7>(tmp_8_cast6_fu_1107_p1.read()));
}

void matmul_hw::thread_tmp_21_cast_fu_813_p1() {
    tmp_21_cast_fu_813_p1 = esl_zext<64,6>(tmp_19_fu_807_p2.read());
}

void matmul_hw::thread_tmp_22_cast_fu_1116_p1() {
    tmp_22_cast_fu_1116_p1 = esl_zext<64,7>(tmp_20_fu_1110_p2.read());
}

void matmul_hw::thread_tmp_2_cast_fu_1103_p1() {
    tmp_2_cast_fu_1103_p1 = esl_zext<7,6>(tmp_1_fu_1094_p4.read());
}

void matmul_hw::thread_tmp_2_fu_338_p1() {
    tmp_2_fu_338_p1 = esl_zext<64,5>(tmp_3_fu_330_p3.read());
}

void matmul_hw::thread_tmp_2_mid2_v_v_v_fu_322_p3() {
    tmp_2_mid2_v_v_v_fu_322_p3 = (!exitcond_fu_296_p2.read()[0].is_01())? sc_lv<3>(): ((exitcond_fu_296_p2.read()[0].to_bool())? i_1_fu_290_p2.read(): i_reg_255.read());
}

void matmul_hw::thread_tmp_3_fu_330_p3() {
    tmp_3_fu_330_p3 = esl_concat<3,2>(tmp_2_mid2_v_v_v_fu_322_p3.read(), ap_const_lv2_0);
}

void matmul_hw::thread_tmp_5_fu_429_p2() {
    tmp_5_fu_429_p2 = (!j_mid2_reg_1337.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(j_mid2_reg_1337.read() == ap_const_lv3_0);
}

void matmul_hw::thread_tmp_6_fu_591_p1() {
    tmp_6_fu_591_p1 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_0_3_15_fu_555_p3.read(): b_copy_0_3_11_fu_104.read());
}

void matmul_hw::thread_tmp_6_fu_591_p2() {
    tmp_6_fu_591_p2 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_0_3_14_fu_547_p3.read(): b_copy_0_3_8_fu_108.read());
}

void matmul_hw::thread_tmp_6_fu_591_p3() {
    tmp_6_fu_591_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_0_3_7_fu_531_p3.read(): b_copy_0_3_12_fu_112.read());
}

void matmul_hw::thread_tmp_6_fu_591_p4() {
    tmp_6_fu_591_p4 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_0_3_2_fu_507_p3.read(): b_copy_0_3_1_fu_116.read());
}

void matmul_hw::thread_tmp_7_fu_759_p1() {
    tmp_7_fu_759_p1 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_1_3_15_fu_720_p3.read(): b_copy_1_3_11_fu_120.read());
}

void matmul_hw::thread_tmp_7_fu_759_p2() {
    tmp_7_fu_759_p2 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_1_3_14_fu_713_p3.read(): b_copy_1_3_8_fu_124.read());
}

void matmul_hw::thread_tmp_7_fu_759_p3() {
    tmp_7_fu_759_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_1_3_7_fu_699_p3.read(): b_copy_1_3_12_fu_128.read());
}

void matmul_hw::thread_tmp_7_fu_759_p4() {
    tmp_7_fu_759_p4 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_1_3_2_fu_678_p3.read(): b_copy_1_3_1_fu_132.read());
}

void matmul_hw::thread_tmp_8_cast5_fu_804_p1() {
    tmp_8_cast5_fu_804_p1 = esl_zext<6,3>(j_mid2_reg_1337.read());
}

void matmul_hw::thread_tmp_8_cast6_fu_1107_p1() {
    tmp_8_cast6_fu_1107_p1 = esl_zext<7,3>(j_mid2_reg_1337.read());
}

void matmul_hw::thread_tmp_8_cast_fu_462_p1() {
    tmp_8_cast_fu_462_p1 = esl_zext<5,3>(j_mid2_reg_1337.read());
}

void matmul_hw::thread_tmp_8_fu_343_p2() {
    tmp_8_fu_343_p2 = (tmp_3_reg_1295.read() | ap_const_lv5_1);
}

void matmul_hw::thread_tmp_9_fu_913_p1() {
    tmp_9_fu_913_p1 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_2_3_15_fu_874_p3.read(): b_copy_2_3_11_fu_136.read());
}

void matmul_hw::thread_tmp_9_fu_913_p2() {
    tmp_9_fu_913_p2 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_2_3_14_fu_867_p3.read(): b_copy_2_3_8_fu_140.read());
}

void matmul_hw::thread_tmp_9_fu_913_p3() {
    tmp_9_fu_913_p3 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_2_3_7_fu_853_p3.read(): b_copy_2_3_12_fu_144.read());
}

void matmul_hw::thread_tmp_9_fu_913_p4() {
    tmp_9_fu_913_p4 = (!tmp_mid2_reg_1269.read()[0].is_01())? sc_lv<32>(): ((tmp_mid2_reg_1269.read()[0].to_bool())? b_copy_2_3_2_fu_832_p3.read(): b_copy_2_3_1_fu_148.read());
}

void matmul_hw::thread_tmp_fu_401_p1() {
    tmp_fu_401_p1 = j_mid2_fu_385_p3.read().range(2-1, 0);
}

void matmul_hw::thread_tmp_mid1_fu_302_p2() {
    tmp_mid1_fu_302_p2 = (!i_1_fu_290_p2.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(i_1_fu_290_p2.read() == ap_const_lv3_0);
}

void matmul_hw::thread_tmp_mid2_fu_314_p3() {
    tmp_mid2_fu_314_p3 = (!exitcond_fu_296_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_fu_296_p2.read()[0].to_bool())? tmp_mid1_fu_302_p2.read(): tmp1_fu_308_p2.read());
}

void matmul_hw::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(exitcond_flatten_fu_278_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state18;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<18>) ("XXXXXXXXXXXXXXXXXX");
            break;
    }
}

void matmul_hw::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_Addr_A\" :  \"" << a_Addr_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_EN_A\" :  \"" << a_EN_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_WEN_A\" :  \"" << a_WEN_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_Din_A\" :  \"" << a_Din_A.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"a_Dout_A\" :  \"" << a_Dout_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_Clk_A\" :  \"" << a_Clk_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_Rst_A\" :  \"" << a_Rst_A.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

