// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matmul,hls_ip_2016_4,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.516400,HLS_SYN_LAT=1304,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=11,HLS_SYN_FF=2895,HLS_SYN_LUT=2583}" *)

module matmul (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        a_address1,
        a_ce1,
        a_q1,
        b_address0,
        b_ce0,
        b_q0,
        b_address1,
        b_ce1,
        b_q1,
        c_address0,
        c_ce0,
        c_we0,
        c_d0
);

parameter    ap_ST_fsm_state1 = 9'b1;
parameter    ap_ST_fsm_pp0_stage0 = 9'b10;
parameter    ap_ST_fsm_pp0_stage1 = 9'b100;
parameter    ap_ST_fsm_pp0_stage2 = 9'b1000;
parameter    ap_ST_fsm_pp0_stage3 = 9'b10000;
parameter    ap_ST_fsm_pp0_stage4 = 9'b100000;
parameter    ap_ST_fsm_pp0_stage5 = 9'b1000000;
parameter    ap_ST_fsm_pp0_stage6 = 9'b10000000;
parameter    ap_ST_fsm_state129 = 9'b100000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv8_A9 = 8'b10101001;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv4_D = 4'b1101;
parameter    ap_const_lv9_D = 9'b1101;
parameter    ap_const_lv5_D = 5'b1101;
parameter    ap_const_lv6_1A = 6'b11010;
parameter    ap_const_lv8_2 = 8'b10;
parameter    ap_const_lv8_3 = 8'b11;
parameter    ap_const_lv6_27 = 6'b100111;
parameter    ap_const_lv7_34 = 7'b110100;
parameter    ap_const_lv8_4 = 8'b100;
parameter    ap_const_lv8_5 = 8'b101;
parameter    ap_const_lv7_41 = 7'b1000001;
parameter    ap_const_lv7_4E = 7'b1001110;
parameter    ap_const_lv8_6 = 8'b110;
parameter    ap_const_lv8_7 = 8'b111;
parameter    ap_const_lv7_5B = 7'b1011011;
parameter    ap_const_lv6_28 = 6'b101000;
parameter    ap_const_lv8_8 = 8'b1000;
parameter    ap_const_lv8_9 = 8'b1001;
parameter    ap_const_lv8_75 = 8'b1110101;
parameter    ap_const_lv8_82 = 8'b10000010;
parameter    ap_const_lv8_A = 8'b1010;
parameter    ap_const_lv8_B = 8'b1011;
parameter    ap_const_lv8_8F = 8'b10001111;
parameter    ap_const_lv8_9C = 8'b10011100;
parameter    ap_const_lv8_C = 8'b1100;
parameter    ap_const_lv32_8 = 32'b1000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] a_address0;
output   a_ce0;
input  [31:0] a_q0;
output  [7:0] a_address1;
output   a_ce1;
input  [31:0] a_q1;
output  [7:0] b_address0;
output   b_ce0;
input  [31:0] b_q0;
output  [7:0] b_address1;
output   b_ce1;
input  [31:0] b_q1;
output  [7:0] c_address0;
output   c_ce0;
output   c_we0;
output  [31:0] c_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] a_address0;
reg a_ce0;
reg[7:0] a_address1;
reg a_ce1;
reg[7:0] b_address0;
reg b_ce0;
reg[7:0] b_address1;
reg b_ce1;
reg c_ce0;
reg c_we0;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg   [7:0] indvar_flatten_reg_336;
reg   [3:0] i_reg_347;
reg   [3:0] j_reg_358;
wire   [0:0] exitcond_flatten_fu_386_p2;
reg   [0:0] exitcond_flatten_reg_698;
wire   [0:0] ap_CS_fsm_pp0_stage0;
reg   [0:0] ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter2_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter3_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter4_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter5_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter8_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter9_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter10_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter11_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter12_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter13_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter14_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter15_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter16_exitcond_flatten_reg_698;
reg   [0:0] ap_pipeline_reg_pp0_iter17_exitcond_flatten_reg_698;
wire   [7:0] indvar_flatten_next_fu_392_p2;
reg   [7:0] indvar_flatten_next_reg_702;
reg    ap_enable_reg_pp0_iter0;
wire   [3:0] j_mid2_fu_410_p3;
reg   [3:0] j_mid2_reg_707;
wire   [3:0] i_cast2_mid2_v_fu_418_p3;
reg   [3:0] i_cast2_mid2_v_reg_717;
wire   [8:0] tmp_fu_429_p2;
reg   [8:0] tmp_reg_723;
wire   [0:0] ap_CS_fsm_pp0_stage1;
wire   [7:0] tmp_38_fu_435_p1;
reg   [7:0] tmp_38_reg_728;
wire   [7:0] tmp_13_fu_439_p2;
reg   [7:0] tmp_13_reg_744;
wire   [5:0] j_cast1_cast4_cast_fu_449_p1;
reg   [5:0] j_cast1_cast4_cast_reg_749;
wire   [4:0] tmp_25_fu_455_p2;
reg   [4:0] tmp_25_reg_760;
wire   [5:0] tmp_26_fu_461_p2;
reg   [5:0] tmp_26_reg_765;
wire   [0:0] ap_CS_fsm_pp0_stage2;
wire   [7:0] tmp_14_fu_475_p2;
reg   [7:0] tmp_14_reg_780;
wire   [7:0] tmp_15_fu_480_p2;
reg   [7:0] tmp_15_reg_785;
wire   [6:0] j_cast1_cast4_fu_485_p1;
reg   [6:0] j_cast1_cast4_reg_790;
wire   [5:0] tmp_27_fu_496_p2;
reg   [5:0] tmp_27_reg_807;
wire   [6:0] tmp_28_fu_501_p2;
reg   [6:0] tmp_28_reg_812;
reg   [31:0] b_load_reg_817;
wire   [0:0] ap_CS_fsm_pp0_stage3;
wire   [7:0] tmp_16_fu_515_p2;
reg   [7:0] tmp_16_reg_832;
wire   [7:0] tmp_17_fu_520_p2;
reg   [7:0] tmp_17_reg_837;
wire   [6:0] tmp_29_fu_533_p2;
reg   [6:0] tmp_29_reg_852;
wire   [6:0] tmp_30_fu_538_p2;
reg   [6:0] tmp_30_reg_857;
reg   [31:0] a_load_reg_862;
reg   [31:0] a_load_1_reg_867;
reg   [31:0] b_load_1_reg_872;
reg   [31:0] b_load_2_reg_877;
wire   [0:0] ap_CS_fsm_pp0_stage4;
wire   [7:0] tmp_18_fu_551_p2;
reg   [7:0] tmp_18_reg_892;
wire   [7:0] tmp_19_fu_556_p2;
reg   [7:0] tmp_19_reg_897;
wire   [6:0] tmp_31_fu_569_p2;
reg   [6:0] tmp_31_reg_912;
wire   [5:0] tmp_32_fu_574_p2;
reg   [5:0] tmp_32_reg_917;
reg   [31:0] a_load_2_reg_922;
reg   [31:0] a_load_3_reg_927;
reg   [31:0] b_load_3_reg_932;
reg   [31:0] b_load_4_reg_937;
wire   [0:0] ap_CS_fsm_pp0_stage5;
wire   [7:0] tmp_20_fu_587_p2;
reg   [7:0] tmp_20_reg_952;
wire   [7:0] tmp_21_fu_592_p2;
reg   [7:0] tmp_21_reg_957;
wire   [7:0] j_cast1_cast5_fu_597_p1;
reg   [7:0] j_cast1_cast5_reg_962;
wire   [7:0] tmp_33_fu_612_p2;
reg   [7:0] tmp_33_reg_979;
wire   [7:0] tmp_34_fu_618_p2;
reg   [7:0] tmp_34_reg_984;
reg   [31:0] a_load_4_reg_989;
reg   [31:0] a_load_5_reg_994;
reg   [31:0] b_load_5_reg_999;
reg   [31:0] b_load_6_reg_1004;
wire   [3:0] j_1_fu_624_p2;
reg   [3:0] j_1_reg_1009;
wire   [0:0] ap_CS_fsm_pp0_stage6;
wire   [7:0] tmp_22_fu_637_p2;
reg   [7:0] tmp_22_reg_1024;
wire   [7:0] tmp_23_fu_642_p2;
reg   [7:0] tmp_23_reg_1029;
wire   [7:0] tmp_35_fu_655_p2;
reg   [7:0] tmp_35_reg_1044;
wire   [7:0] tmp_36_fu_660_p2;
reg   [7:0] tmp_36_reg_1049;
reg   [31:0] a_load_6_reg_1054;
reg   [31:0] a_load_7_reg_1059;
reg   [31:0] b_load_7_reg_1064;
reg   [31:0] b_load_8_reg_1069;
wire   [7:0] tmp_24_fu_673_p2;
reg   [7:0] tmp_24_reg_1084;
wire   [7:0] tmp_37_fu_686_p2;
reg   [7:0] tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter2_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter3_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter4_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter5_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter6_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter7_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter8_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter9_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter10_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter11_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter12_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter13_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter14_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter15_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter16_tmp_37_reg_1099;
reg   [7:0] ap_pipeline_reg_pp0_iter17_tmp_37_reg_1099;
reg   [31:0] a_load_8_reg_1104;
reg    ap_enable_reg_pp0_iter1;
reg   [31:0] a_load_9_reg_1109;
reg   [31:0] b_load_9_reg_1114;
reg   [31:0] b_load_10_reg_1119;
wire   [31:0] grp_fu_378_p2;
reg   [31:0] tmp1_reg_1129;
wire   [31:0] grp_fu_382_p2;
reg   [31:0] tmp_1_reg_1134;
reg   [31:0] ap_pipeline_reg_pp0_iter2_tmp_1_reg_1134;
reg   [31:0] a_load_10_reg_1139;
reg   [31:0] a_load_11_reg_1144;
reg   [31:0] b_load_11_reg_1149;
reg   [31:0] b_load_12_reg_1154;
reg   [31:0] tmp_2_reg_1159;
reg   [31:0] ap_pipeline_reg_pp0_iter2_tmp_2_reg_1159;
reg   [31:0] ap_pipeline_reg_pp0_iter3_tmp_2_reg_1159;
reg   [31:0] tmp_3_reg_1164;
reg   [31:0] ap_pipeline_reg_pp0_iter2_tmp_3_reg_1164;
reg   [31:0] ap_pipeline_reg_pp0_iter3_tmp_3_reg_1164;
reg   [31:0] ap_pipeline_reg_pp0_iter4_tmp_3_reg_1164;
reg   [31:0] a_load_12_reg_1169;
reg   [31:0] tmp_4_reg_1174;
reg   [31:0] ap_pipeline_reg_pp0_iter2_tmp_4_reg_1174;
reg   [31:0] ap_pipeline_reg_pp0_iter3_tmp_4_reg_1174;
reg   [31:0] ap_pipeline_reg_pp0_iter4_tmp_4_reg_1174;
reg   [31:0] ap_pipeline_reg_pp0_iter5_tmp_4_reg_1174;
reg   [31:0] tmp_5_reg_1179;
reg   [31:0] ap_pipeline_reg_pp0_iter2_tmp_5_reg_1179;
reg   [31:0] ap_pipeline_reg_pp0_iter3_tmp_5_reg_1179;
reg   [31:0] ap_pipeline_reg_pp0_iter4_tmp_5_reg_1179;
reg   [31:0] ap_pipeline_reg_pp0_iter5_tmp_5_reg_1179;
reg   [31:0] ap_pipeline_reg_pp0_iter6_tmp_5_reg_1179;
reg   [31:0] ap_pipeline_reg_pp0_iter7_tmp_5_reg_1179;
reg   [31:0] tmp_6_reg_1184;
reg   [31:0] ap_pipeline_reg_pp0_iter2_tmp_6_reg_1184;
reg   [31:0] ap_pipeline_reg_pp0_iter3_tmp_6_reg_1184;
reg   [31:0] ap_pipeline_reg_pp0_iter4_tmp_6_reg_1184;
reg   [31:0] ap_pipeline_reg_pp0_iter5_tmp_6_reg_1184;
reg   [31:0] ap_pipeline_reg_pp0_iter6_tmp_6_reg_1184;
reg   [31:0] ap_pipeline_reg_pp0_iter7_tmp_6_reg_1184;
reg   [31:0] ap_pipeline_reg_pp0_iter8_tmp_6_reg_1184;
reg   [31:0] tmp_7_reg_1189;
reg   [31:0] ap_pipeline_reg_pp0_iter2_tmp_7_reg_1189;
reg   [31:0] ap_pipeline_reg_pp0_iter3_tmp_7_reg_1189;
reg   [31:0] ap_pipeline_reg_pp0_iter4_tmp_7_reg_1189;
reg   [31:0] ap_pipeline_reg_pp0_iter5_tmp_7_reg_1189;
reg   [31:0] ap_pipeline_reg_pp0_iter6_tmp_7_reg_1189;
reg   [31:0] ap_pipeline_reg_pp0_iter7_tmp_7_reg_1189;
reg   [31:0] ap_pipeline_reg_pp0_iter8_tmp_7_reg_1189;
reg   [31:0] ap_pipeline_reg_pp0_iter9_tmp_7_reg_1189;
reg   [31:0] tmp_8_reg_1194;
reg   [31:0] ap_pipeline_reg_pp0_iter2_tmp_8_reg_1194;
reg   [31:0] ap_pipeline_reg_pp0_iter3_tmp_8_reg_1194;
reg   [31:0] ap_pipeline_reg_pp0_iter4_tmp_8_reg_1194;
reg   [31:0] ap_pipeline_reg_pp0_iter5_tmp_8_reg_1194;
reg   [31:0] ap_pipeline_reg_pp0_iter6_tmp_8_reg_1194;
reg   [31:0] ap_pipeline_reg_pp0_iter7_tmp_8_reg_1194;
reg   [31:0] ap_pipeline_reg_pp0_iter8_tmp_8_reg_1194;
reg   [31:0] ap_pipeline_reg_pp0_iter9_tmp_8_reg_1194;
reg   [31:0] ap_pipeline_reg_pp0_iter10_tmp_8_reg_1194;
reg   [31:0] tmp_9_reg_1199;
reg   [31:0] ap_pipeline_reg_pp0_iter2_tmp_9_reg_1199;
reg   [31:0] ap_pipeline_reg_pp0_iter3_tmp_9_reg_1199;
reg   [31:0] ap_pipeline_reg_pp0_iter4_tmp_9_reg_1199;
reg   [31:0] ap_pipeline_reg_pp0_iter5_tmp_9_reg_1199;
reg   [31:0] ap_pipeline_reg_pp0_iter6_tmp_9_reg_1199;
reg   [31:0] ap_pipeline_reg_pp0_iter7_tmp_9_reg_1199;
reg   [31:0] ap_pipeline_reg_pp0_iter8_tmp_9_reg_1199;
reg   [31:0] ap_pipeline_reg_pp0_iter9_tmp_9_reg_1199;
reg   [31:0] ap_pipeline_reg_pp0_iter10_tmp_9_reg_1199;
reg   [31:0] ap_pipeline_reg_pp0_iter11_tmp_9_reg_1199;
reg   [31:0] ap_pipeline_reg_pp0_iter12_tmp_9_reg_1199;
reg   [31:0] tmp_s_reg_1204;
reg   [31:0] ap_pipeline_reg_pp0_iter2_tmp_s_reg_1204;
reg   [31:0] ap_pipeline_reg_pp0_iter3_tmp_s_reg_1204;
reg   [31:0] ap_pipeline_reg_pp0_iter4_tmp_s_reg_1204;
reg   [31:0] ap_pipeline_reg_pp0_iter5_tmp_s_reg_1204;
reg   [31:0] ap_pipeline_reg_pp0_iter6_tmp_s_reg_1204;
reg   [31:0] ap_pipeline_reg_pp0_iter7_tmp_s_reg_1204;
reg   [31:0] ap_pipeline_reg_pp0_iter8_tmp_s_reg_1204;
reg   [31:0] ap_pipeline_reg_pp0_iter9_tmp_s_reg_1204;
reg   [31:0] ap_pipeline_reg_pp0_iter10_tmp_s_reg_1204;
reg   [31:0] ap_pipeline_reg_pp0_iter11_tmp_s_reg_1204;
reg   [31:0] ap_pipeline_reg_pp0_iter12_tmp_s_reg_1204;
reg   [31:0] ap_pipeline_reg_pp0_iter13_tmp_s_reg_1204;
reg   [31:0] tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter2_tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter3_tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter4_tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter5_tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter6_tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter7_tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter8_tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter9_tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter10_tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter11_tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter12_tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter13_tmp_10_reg_1209;
reg   [31:0] ap_pipeline_reg_pp0_iter14_tmp_10_reg_1209;
reg   [31:0] tmp_11_reg_1214;
reg    ap_enable_reg_pp0_iter2;
reg   [31:0] ap_pipeline_reg_pp0_iter3_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter4_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter5_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter6_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter7_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter8_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter9_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter10_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter11_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter12_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter13_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter14_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter15_tmp_11_reg_1214;
reg   [31:0] ap_pipeline_reg_pp0_iter16_tmp_11_reg_1214;
wire   [31:0] grp_fu_369_p2;
reg   [31:0] sum_mult_1_reg_1219;
reg   [31:0] sum_mult_1_1_reg_1224;
reg    ap_enable_reg_pp0_iter3;
reg   [31:0] sum_mult_1_2_reg_1229;
reg    ap_enable_reg_pp0_iter5;
reg   [31:0] sum_mult_1_3_reg_1234;
reg    ap_enable_reg_pp0_iter6;
reg   [31:0] sum_mult_1_4_reg_1239;
reg    ap_enable_reg_pp0_iter7;
reg   [31:0] sum_mult_1_5_reg_1244;
reg    ap_enable_reg_pp0_iter8;
reg   [31:0] sum_mult_1_6_reg_1249;
reg    ap_enable_reg_pp0_iter10;
wire   [31:0] grp_fu_374_p2;
reg   [31:0] sum_mult_1_7_reg_1254;
reg    ap_enable_reg_pp0_iter11;
reg   [31:0] sum_mult_1_8_reg_1259;
reg    ap_enable_reg_pp0_iter12;
reg   [31:0] sum_mult_1_9_reg_1264;
reg    ap_enable_reg_pp0_iter14;
reg   [31:0] sum_mult_1_s_reg_1269;
reg    ap_enable_reg_pp0_iter15;
reg   [31:0] sum_mult_1_10_reg_1274;
reg    ap_enable_reg_pp0_iter16;
reg   [31:0] sum_mult_1_11_reg_1279;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter18;
reg   [7:0] indvar_flatten_phi_fu_340_p4;
reg   [3:0] i_phi_fu_351_p4;
reg   [3:0] j_phi_fu_362_p4;
wire   [31:0] j_cast1_fu_445_p1;
wire   [31:0] tmp_cast_fu_467_p1;
wire   [31:0] tmp_13_cast_fu_471_p1;
wire   [31:0] tmp_25_cast_fu_488_p1;
wire   [31:0] tmp_26_cast_fu_492_p1;
wire   [31:0] tmp_14_cast_fu_507_p1;
wire   [31:0] tmp_15_cast_fu_511_p1;
wire   [31:0] tmp_27_cast_fu_525_p1;
wire   [31:0] tmp_28_cast_fu_529_p1;
wire   [31:0] tmp_16_cast_fu_543_p1;
wire   [31:0] tmp_17_cast_fu_547_p1;
wire   [31:0] tmp_29_cast_fu_561_p1;
wire   [31:0] tmp_30_cast_fu_565_p1;
wire   [31:0] tmp_18_cast_fu_579_p1;
wire   [31:0] tmp_19_cast_fu_583_p1;
wire   [31:0] tmp_31_cast_fu_600_p1;
wire   [31:0] tmp_32_cast_fu_607_p1;
wire   [31:0] tmp_20_cast_fu_629_p1;
wire   [31:0] tmp_21_cast_fu_633_p1;
wire   [31:0] tmp_33_cast_fu_647_p1;
wire   [31:0] tmp_34_cast_fu_651_p1;
wire   [31:0] tmp_22_cast_fu_665_p1;
wire   [31:0] tmp_23_cast_fu_669_p1;
wire   [31:0] tmp_35_cast_fu_678_p1;
wire   [31:0] tmp_36_cast_fu_682_p1;
wire   [31:0] tmp_24_cast_fu_690_p1;
wire   [31:0] tmp_37_cast_fu_694_p1;
reg   [31:0] grp_fu_369_p0;
reg   [31:0] grp_fu_369_p1;
reg   [31:0] grp_fu_374_p0;
reg   [31:0] grp_fu_374_p1;
reg   [31:0] grp_fu_378_p0;
reg   [31:0] grp_fu_378_p1;
reg   [31:0] grp_fu_382_p0;
reg   [31:0] grp_fu_382_p1;
wire   [0:0] exitcond_fu_404_p2;
wire   [3:0] i_1_fu_398_p2;
wire   [3:0] tmp_fu_429_p1;
wire   [4:0] j_cast1_cast_fu_452_p1;
wire  signed [6:0] tmp_32_cast7_fu_604_p1;
wire   [0:0] ap_CS_fsm_state129;
reg   [8:0] ap_NS_fsm;
wire   [8:0] tmp_fu_429_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'b1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
end

matmul_fadd_32ns_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matmul_fadd_32ns_bkb_U0(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_369_p0),
    .din1(grp_fu_369_p1),
    .ce(1'b1),
    .dout(grp_fu_369_p2)
);

matmul_fadd_32ns_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matmul_fadd_32ns_bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_374_p0),
    .din1(grp_fu_374_p1),
    .ce(1'b1),
    .dout(grp_fu_374_p2)
);

matmul_fmul_32ns_cud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matmul_fmul_32ns_cud_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_378_p0),
    .din1(grp_fu_378_p1),
    .ce(1'b1),
    .dout(grp_fu_378_p2)
);

matmul_fmul_32ns_cud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matmul_fmul_32ns_cud_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_382_p0),
    .din1(grp_fu_382_p1),
    .ce(1'b1),
    .dout(grp_fu_382_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(exitcond_flatten_fu_386_p2 == 1'b0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end else if ((((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & ~(exitcond_flatten_reg_698 == 1'b0)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
            ap_enable_reg_pp0_iter18 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        i_reg_347 <= i_cast2_mid2_v_reg_717;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        i_reg_347 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        indvar_flatten_reg_336 <= indvar_flatten_next_reg_702;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        indvar_flatten_reg_336 <= ap_const_lv8_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        j_reg_358 <= j_1_reg_1009;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        j_reg_358 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_698 == 1'b0))) begin
        a_load_10_reg_1139 <= a_q0;
        a_load_11_reg_1144 <= a_q1;
        b_load_11_reg_1149 <= b_q0;
        b_load_12_reg_1154 <= b_q1;
        tmp1_reg_1129 <= grp_fu_378_p2;
        tmp_1_reg_1134 <= grp_fu_382_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_698 == 1'b0))) begin
        a_load_12_reg_1169 <= a_q0;
        tmp_2_reg_1159 <= grp_fu_378_p2;
        tmp_3_reg_1164 <= grp_fu_382_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        a_load_1_reg_867 <= a_q0;
        a_load_reg_862 <= a_q1;
        b_load_1_reg_872 <= b_q1;
        b_load_2_reg_877 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        a_load_2_reg_922 <= a_q1;
        a_load_3_reg_927 <= a_q0;
        b_load_3_reg_932 <= b_q1;
        b_load_4_reg_937 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        a_load_4_reg_989 <= a_q1;
        a_load_5_reg_994 <= a_q0;
        b_load_5_reg_999 <= b_q1;
        b_load_6_reg_1004 <= b_q0;
        j_1_reg_1009 <= j_1_fu_624_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        a_load_6_reg_1054 <= a_q1;
        a_load_7_reg_1059 <= a_q0;
        b_load_7_reg_1064 <= b_q1;
        b_load_8_reg_1069 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        a_load_8_reg_1104 <= a_q1;
        a_load_9_reg_1109 <= a_q0;
        b_load_10_reg_1119 <= b_q0;
        b_load_9_reg_1114 <= b_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_pipeline_reg_pp0_iter10_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter9_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter10_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter9_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter10_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter9_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter11_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter10_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter11_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter10_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter11_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter10_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter12_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter11_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter12_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter11_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter12_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter11_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter13_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter12_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter13_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter12_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter13_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter12_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter14_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter13_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter14_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter13_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter14_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter13_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter15_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter14_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter15_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter14_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter15_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter14_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter16_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter15_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter16_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter15_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter16_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter15_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter17_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter16_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter17_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter16_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_698 <= exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter2_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter2_tmp_37_reg_1099 <= tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter3_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter2_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter3_tmp_11_reg_1214 <= tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter3_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter2_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter4_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter3_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter4_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter3_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter4_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter3_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter5_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter4_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter5_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter4_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter5_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter4_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter5_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter6_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter5_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter6_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter5_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter7_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter6_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter7_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter6_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter8_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter8_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter7_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter8_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter7_tmp_37_reg_1099;
        ap_pipeline_reg_pp0_iter9_exitcond_flatten_reg_698 <= ap_pipeline_reg_pp0_iter8_exitcond_flatten_reg_698;
        ap_pipeline_reg_pp0_iter9_tmp_11_reg_1214 <= ap_pipeline_reg_pp0_iter8_tmp_11_reg_1214;
        ap_pipeline_reg_pp0_iter9_tmp_37_reg_1099 <= ap_pipeline_reg_pp0_iter8_tmp_37_reg_1099;
        exitcond_flatten_reg_698 <= exitcond_flatten_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
        ap_pipeline_reg_pp0_iter10_tmp_10_reg_1209 <= ap_pipeline_reg_pp0_iter9_tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter10_tmp_s_reg_1204 <= ap_pipeline_reg_pp0_iter9_tmp_s_reg_1204;
        ap_pipeline_reg_pp0_iter11_tmp_10_reg_1209 <= ap_pipeline_reg_pp0_iter10_tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter11_tmp_s_reg_1204 <= ap_pipeline_reg_pp0_iter10_tmp_s_reg_1204;
        ap_pipeline_reg_pp0_iter12_tmp_10_reg_1209 <= ap_pipeline_reg_pp0_iter11_tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter12_tmp_s_reg_1204 <= ap_pipeline_reg_pp0_iter11_tmp_s_reg_1204;
        ap_pipeline_reg_pp0_iter13_tmp_10_reg_1209 <= ap_pipeline_reg_pp0_iter12_tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter13_tmp_s_reg_1204 <= ap_pipeline_reg_pp0_iter12_tmp_s_reg_1204;
        ap_pipeline_reg_pp0_iter14_tmp_10_reg_1209 <= ap_pipeline_reg_pp0_iter13_tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter2_tmp_10_reg_1209 <= tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter2_tmp_s_reg_1204 <= tmp_s_reg_1204;
        ap_pipeline_reg_pp0_iter3_tmp_10_reg_1209 <= ap_pipeline_reg_pp0_iter2_tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter3_tmp_s_reg_1204 <= ap_pipeline_reg_pp0_iter2_tmp_s_reg_1204;
        ap_pipeline_reg_pp0_iter4_tmp_10_reg_1209 <= ap_pipeline_reg_pp0_iter3_tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter4_tmp_s_reg_1204 <= ap_pipeline_reg_pp0_iter3_tmp_s_reg_1204;
        ap_pipeline_reg_pp0_iter5_tmp_10_reg_1209 <= ap_pipeline_reg_pp0_iter4_tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter5_tmp_s_reg_1204 <= ap_pipeline_reg_pp0_iter4_tmp_s_reg_1204;
        ap_pipeline_reg_pp0_iter6_tmp_10_reg_1209 <= ap_pipeline_reg_pp0_iter5_tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter6_tmp_s_reg_1204 <= ap_pipeline_reg_pp0_iter5_tmp_s_reg_1204;
        ap_pipeline_reg_pp0_iter7_tmp_10_reg_1209 <= ap_pipeline_reg_pp0_iter6_tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter7_tmp_s_reg_1204 <= ap_pipeline_reg_pp0_iter6_tmp_s_reg_1204;
        ap_pipeline_reg_pp0_iter8_tmp_10_reg_1209 <= ap_pipeline_reg_pp0_iter7_tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter8_tmp_s_reg_1204 <= ap_pipeline_reg_pp0_iter7_tmp_s_reg_1204;
        ap_pipeline_reg_pp0_iter9_tmp_10_reg_1209 <= ap_pipeline_reg_pp0_iter8_tmp_10_reg_1209;
        ap_pipeline_reg_pp0_iter9_tmp_s_reg_1204 <= ap_pipeline_reg_pp0_iter8_tmp_s_reg_1204;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage5)) begin
        ap_pipeline_reg_pp0_iter10_tmp_8_reg_1194 <= ap_pipeline_reg_pp0_iter9_tmp_8_reg_1194;
        ap_pipeline_reg_pp0_iter10_tmp_9_reg_1199 <= ap_pipeline_reg_pp0_iter9_tmp_9_reg_1199;
        ap_pipeline_reg_pp0_iter11_tmp_9_reg_1199 <= ap_pipeline_reg_pp0_iter10_tmp_9_reg_1199;
        ap_pipeline_reg_pp0_iter12_tmp_9_reg_1199 <= ap_pipeline_reg_pp0_iter11_tmp_9_reg_1199;
        ap_pipeline_reg_pp0_iter2_tmp_8_reg_1194 <= tmp_8_reg_1194;
        ap_pipeline_reg_pp0_iter2_tmp_9_reg_1199 <= tmp_9_reg_1199;
        ap_pipeline_reg_pp0_iter3_tmp_8_reg_1194 <= ap_pipeline_reg_pp0_iter2_tmp_8_reg_1194;
        ap_pipeline_reg_pp0_iter3_tmp_9_reg_1199 <= ap_pipeline_reg_pp0_iter2_tmp_9_reg_1199;
        ap_pipeline_reg_pp0_iter4_tmp_8_reg_1194 <= ap_pipeline_reg_pp0_iter3_tmp_8_reg_1194;
        ap_pipeline_reg_pp0_iter4_tmp_9_reg_1199 <= ap_pipeline_reg_pp0_iter3_tmp_9_reg_1199;
        ap_pipeline_reg_pp0_iter5_tmp_8_reg_1194 <= ap_pipeline_reg_pp0_iter4_tmp_8_reg_1194;
        ap_pipeline_reg_pp0_iter5_tmp_9_reg_1199 <= ap_pipeline_reg_pp0_iter4_tmp_9_reg_1199;
        ap_pipeline_reg_pp0_iter6_tmp_8_reg_1194 <= ap_pipeline_reg_pp0_iter5_tmp_8_reg_1194;
        ap_pipeline_reg_pp0_iter6_tmp_9_reg_1199 <= ap_pipeline_reg_pp0_iter5_tmp_9_reg_1199;
        ap_pipeline_reg_pp0_iter7_tmp_8_reg_1194 <= ap_pipeline_reg_pp0_iter6_tmp_8_reg_1194;
        ap_pipeline_reg_pp0_iter7_tmp_9_reg_1199 <= ap_pipeline_reg_pp0_iter6_tmp_9_reg_1199;
        ap_pipeline_reg_pp0_iter8_tmp_8_reg_1194 <= ap_pipeline_reg_pp0_iter7_tmp_8_reg_1194;
        ap_pipeline_reg_pp0_iter8_tmp_9_reg_1199 <= ap_pipeline_reg_pp0_iter7_tmp_9_reg_1199;
        ap_pipeline_reg_pp0_iter9_tmp_8_reg_1194 <= ap_pipeline_reg_pp0_iter8_tmp_8_reg_1194;
        ap_pipeline_reg_pp0_iter9_tmp_9_reg_1199 <= ap_pipeline_reg_pp0_iter8_tmp_9_reg_1199;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
        ap_pipeline_reg_pp0_iter2_tmp_1_reg_1134 <= tmp_1_reg_1134;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
        ap_pipeline_reg_pp0_iter2_tmp_2_reg_1159 <= tmp_2_reg_1159;
        ap_pipeline_reg_pp0_iter2_tmp_3_reg_1164 <= tmp_3_reg_1164;
        ap_pipeline_reg_pp0_iter3_tmp_2_reg_1159 <= ap_pipeline_reg_pp0_iter2_tmp_2_reg_1159;
        ap_pipeline_reg_pp0_iter3_tmp_3_reg_1164 <= ap_pipeline_reg_pp0_iter2_tmp_3_reg_1164;
        ap_pipeline_reg_pp0_iter4_tmp_3_reg_1164 <= ap_pipeline_reg_pp0_iter3_tmp_3_reg_1164;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
        ap_pipeline_reg_pp0_iter2_tmp_4_reg_1174 <= tmp_4_reg_1174;
        ap_pipeline_reg_pp0_iter2_tmp_5_reg_1179 <= tmp_5_reg_1179;
        ap_pipeline_reg_pp0_iter3_tmp_4_reg_1174 <= ap_pipeline_reg_pp0_iter2_tmp_4_reg_1174;
        ap_pipeline_reg_pp0_iter3_tmp_5_reg_1179 <= ap_pipeline_reg_pp0_iter2_tmp_5_reg_1179;
        ap_pipeline_reg_pp0_iter4_tmp_4_reg_1174 <= ap_pipeline_reg_pp0_iter3_tmp_4_reg_1174;
        ap_pipeline_reg_pp0_iter4_tmp_5_reg_1179 <= ap_pipeline_reg_pp0_iter3_tmp_5_reg_1179;
        ap_pipeline_reg_pp0_iter5_tmp_4_reg_1174 <= ap_pipeline_reg_pp0_iter4_tmp_4_reg_1174;
        ap_pipeline_reg_pp0_iter5_tmp_5_reg_1179 <= ap_pipeline_reg_pp0_iter4_tmp_5_reg_1179;
        ap_pipeline_reg_pp0_iter6_tmp_5_reg_1179 <= ap_pipeline_reg_pp0_iter5_tmp_5_reg_1179;
        ap_pipeline_reg_pp0_iter7_tmp_5_reg_1179 <= ap_pipeline_reg_pp0_iter6_tmp_5_reg_1179;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage4)) begin
        ap_pipeline_reg_pp0_iter2_tmp_6_reg_1184 <= tmp_6_reg_1184;
        ap_pipeline_reg_pp0_iter2_tmp_7_reg_1189 <= tmp_7_reg_1189;
        ap_pipeline_reg_pp0_iter3_tmp_6_reg_1184 <= ap_pipeline_reg_pp0_iter2_tmp_6_reg_1184;
        ap_pipeline_reg_pp0_iter3_tmp_7_reg_1189 <= ap_pipeline_reg_pp0_iter2_tmp_7_reg_1189;
        ap_pipeline_reg_pp0_iter4_tmp_6_reg_1184 <= ap_pipeline_reg_pp0_iter3_tmp_6_reg_1184;
        ap_pipeline_reg_pp0_iter4_tmp_7_reg_1189 <= ap_pipeline_reg_pp0_iter3_tmp_7_reg_1189;
        ap_pipeline_reg_pp0_iter5_tmp_6_reg_1184 <= ap_pipeline_reg_pp0_iter4_tmp_6_reg_1184;
        ap_pipeline_reg_pp0_iter5_tmp_7_reg_1189 <= ap_pipeline_reg_pp0_iter4_tmp_7_reg_1189;
        ap_pipeline_reg_pp0_iter6_tmp_6_reg_1184 <= ap_pipeline_reg_pp0_iter5_tmp_6_reg_1184;
        ap_pipeline_reg_pp0_iter6_tmp_7_reg_1189 <= ap_pipeline_reg_pp0_iter5_tmp_7_reg_1189;
        ap_pipeline_reg_pp0_iter7_tmp_6_reg_1184 <= ap_pipeline_reg_pp0_iter6_tmp_6_reg_1184;
        ap_pipeline_reg_pp0_iter7_tmp_7_reg_1189 <= ap_pipeline_reg_pp0_iter6_tmp_7_reg_1189;
        ap_pipeline_reg_pp0_iter8_tmp_6_reg_1184 <= ap_pipeline_reg_pp0_iter7_tmp_6_reg_1184;
        ap_pipeline_reg_pp0_iter8_tmp_7_reg_1189 <= ap_pipeline_reg_pp0_iter7_tmp_7_reg_1189;
        ap_pipeline_reg_pp0_iter9_tmp_7_reg_1189 <= ap_pipeline_reg_pp0_iter8_tmp_7_reg_1189;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_load_reg_817 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_fu_386_p2 == 1'b0))) begin
        i_cast2_mid2_v_reg_717 <= i_cast2_mid2_v_fu_418_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        indvar_flatten_next_reg_702 <= indvar_flatten_next_fu_392_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_698 == 1'b0))) begin
        j_cast1_cast4_cast_reg_749[3 : 0] <= j_cast1_cast4_cast_fu_449_p1[3 : 0];
        tmp_13_reg_744 <= tmp_13_fu_439_p2;
        tmp_25_reg_760 <= tmp_25_fu_455_p2;
        tmp_26_reg_765 <= tmp_26_fu_461_p2;
        tmp_38_reg_728 <= tmp_38_fu_435_p1;
        tmp_reg_723 <= tmp_fu_429_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        j_cast1_cast4_reg_790[3 : 0] <= j_cast1_cast4_fu_485_p1[3 : 0];
        tmp_14_reg_780 <= tmp_14_fu_475_p2;
        tmp_15_reg_785 <= tmp_15_fu_480_p2;
        tmp_27_reg_807 <= tmp_27_fu_496_p2;
        tmp_28_reg_812 <= tmp_28_fu_501_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        j_cast1_cast5_reg_962[3 : 0] <= j_cast1_cast5_fu_597_p1[3 : 0];
        tmp_20_reg_952 <= tmp_20_fu_587_p2;
        tmp_21_reg_957 <= tmp_21_fu_592_p2;
        tmp_33_reg_979 <= tmp_33_fu_612_p2;
        tmp_34_reg_984 <= tmp_34_fu_618_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_fu_386_p2 == 1'b0))) begin
        j_mid2_reg_707 <= j_mid2_fu_410_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter16) & (ap_pipeline_reg_pp0_iter16_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_10_reg_1274 <= grp_fu_374_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_enable_reg_pp0_iter17) & (ap_pipeline_reg_pp0_iter17_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_11_reg_1279 <= grp_fu_374_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter3) & (ap_pipeline_reg_pp0_iter3_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_1_reg_1224 <= grp_fu_369_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter5) & (ap_pipeline_reg_pp0_iter4_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_2_reg_1229 <= grp_fu_369_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter6) & (ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_3_reg_1234 <= grp_fu_369_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter7) & (ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_4_reg_1239 <= grp_fu_369_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_enable_reg_pp0_iter8) & (ap_pipeline_reg_pp0_iter8_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_5_reg_1244 <= grp_fu_369_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter10) & (ap_pipeline_reg_pp0_iter10_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_6_reg_1249 <= grp_fu_369_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter11) & (ap_pipeline_reg_pp0_iter11_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_7_reg_1254 <= grp_fu_374_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter12) & (ap_pipeline_reg_pp0_iter12_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_8_reg_1259 <= grp_fu_374_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter14) & (ap_pipeline_reg_pp0_iter13_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_9_reg_1264 <= grp_fu_374_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter2) & (ap_pipeline_reg_pp0_iter2_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_reg_1219 <= grp_fu_369_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter15) & (ap_pipeline_reg_pp0_iter15_exitcond_flatten_reg_698 == 1'b0))) begin
        sum_mult_1_s_reg_1269 <= grp_fu_374_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_698 == 1'b0))) begin
        tmp_10_reg_1209 <= grp_fu_382_p2;
        tmp_s_reg_1204 <= grp_fu_378_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        tmp_11_reg_1214 <= grp_fu_378_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        tmp_16_reg_832 <= tmp_16_fu_515_p2;
        tmp_17_reg_837 <= tmp_17_fu_520_p2;
        tmp_29_reg_852 <= tmp_29_fu_533_p2;
        tmp_30_reg_857 <= tmp_30_fu_538_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        tmp_18_reg_892 <= tmp_18_fu_551_p2;
        tmp_19_reg_897 <= tmp_19_fu_556_p2;
        tmp_31_reg_912 <= tmp_31_fu_569_p2;
        tmp_32_reg_917 <= tmp_32_fu_574_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        tmp_22_reg_1024 <= tmp_22_fu_637_p2;
        tmp_23_reg_1029 <= tmp_23_fu_642_p2;
        tmp_35_reg_1044 <= tmp_35_fu_655_p2;
        tmp_36_reg_1049 <= tmp_36_fu_660_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_698 == 1'b0))) begin
        tmp_24_reg_1084 <= tmp_24_fu_673_p2;
        tmp_37_reg_1099 <= tmp_37_fu_686_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_698 == 1'b0))) begin
        tmp_4_reg_1174 <= grp_fu_378_p2;
        tmp_5_reg_1179 <= grp_fu_382_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_698 == 1'b0))) begin
        tmp_6_reg_1184 <= grp_fu_378_p2;
        tmp_7_reg_1189 <= grp_fu_382_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_698 == 1'b0))) begin
        tmp_8_reg_1194 <= grp_fu_378_p2;
        tmp_9_reg_1199 <= grp_fu_382_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        a_address0 = tmp_24_cast_fu_690_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        a_address0 = tmp_22_cast_fu_665_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        a_address0 = tmp_21_cast_fu_633_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        a_address0 = tmp_19_cast_fu_583_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        a_address0 = tmp_17_cast_fu_547_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        a_address0 = tmp_15_cast_fu_511_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_address0 = tmp_13_cast_fu_471_p1;
    end else begin
        a_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        a_address1 = tmp_23_cast_fu_669_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        a_address1 = tmp_20_cast_fu_629_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        a_address1 = tmp_18_cast_fu_579_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        a_address1 = tmp_16_cast_fu_543_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        a_address1 = tmp_14_cast_fu_507_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_address1 = tmp_cast_fu_467_p1;
    end else begin
        a_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1)))) begin
        a_ce0 = 1'b1;
    end else begin
        a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1)))) begin
        a_ce1 = 1'b1;
    end else begin
        a_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state129)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state129)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        b_address0 = tmp_35_cast_fu_678_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        b_address0 = tmp_34_cast_fu_651_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        b_address0 = tmp_32_cast_fu_607_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        b_address0 = tmp_30_cast_fu_565_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        b_address0 = tmp_28_cast_fu_529_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_address0 = tmp_26_cast_fu_492_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_address0 = j_cast1_fu_445_p1;
    end else begin
        b_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        b_address1 = tmp_36_cast_fu_682_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        b_address1 = tmp_33_cast_fu_647_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        b_address1 = tmp_31_cast_fu_600_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        b_address1 = tmp_29_cast_fu_561_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        b_address1 = tmp_27_cast_fu_525_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_address1 = tmp_25_cast_fu_488_p1;
    end else begin
        b_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        b_ce0 = 1'b1;
    end else begin
        b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1)))) begin
        b_ce1 = 1'b1;
    end else begin
        b_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter18))) begin
        c_ce0 = 1'b1;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_pipeline_reg_pp0_iter17_exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter18))) begin
        c_we0 = 1'b1;
    end else begin
        c_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter9))) begin
        grp_fu_369_p0 = sum_mult_1_5_reg_1244;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter7))) begin
        grp_fu_369_p0 = sum_mult_1_4_reg_1239;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter6))) begin
        grp_fu_369_p0 = sum_mult_1_3_reg_1234;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter5))) begin
        grp_fu_369_p0 = sum_mult_1_2_reg_1229;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_enable_reg_pp0_iter3))) begin
        grp_fu_369_p0 = sum_mult_1_1_reg_1224;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        grp_fu_369_p0 = sum_mult_1_reg_1219;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_369_p0 = tmp1_reg_1129;
    end else begin
        grp_fu_369_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter9))) begin
        grp_fu_369_p1 = ap_pipeline_reg_pp0_iter8_tmp_6_reg_1184;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter7))) begin
        grp_fu_369_p1 = ap_pipeline_reg_pp0_iter7_tmp_5_reg_1179;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter6))) begin
        grp_fu_369_p1 = ap_pipeline_reg_pp0_iter5_tmp_4_reg_1174;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter5))) begin
        grp_fu_369_p1 = ap_pipeline_reg_pp0_iter4_tmp_3_reg_1164;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_enable_reg_pp0_iter3))) begin
        grp_fu_369_p1 = ap_pipeline_reg_pp0_iter3_tmp_2_reg_1159;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        grp_fu_369_p1 = ap_pipeline_reg_pp0_iter2_tmp_1_reg_1134;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_369_p1 = ap_const_lv32_0;
    end else begin
        grp_fu_369_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter16))) begin
        grp_fu_374_p0 = sum_mult_1_10_reg_1274;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter15))) begin
        grp_fu_374_p0 = sum_mult_1_s_reg_1269;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter14))) begin
        grp_fu_374_p0 = sum_mult_1_9_reg_1264;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_enable_reg_pp0_iter12))) begin
        grp_fu_374_p0 = sum_mult_1_8_reg_1259;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter11))) begin
        grp_fu_374_p0 = sum_mult_1_7_reg_1254;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter10))) begin
        grp_fu_374_p0 = sum_mult_1_6_reg_1249;
    end else begin
        grp_fu_374_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter16))) begin
        grp_fu_374_p1 = ap_pipeline_reg_pp0_iter16_tmp_11_reg_1214;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter15))) begin
        grp_fu_374_p1 = ap_pipeline_reg_pp0_iter14_tmp_10_reg_1209;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter14))) begin
        grp_fu_374_p1 = ap_pipeline_reg_pp0_iter13_tmp_s_reg_1204;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_enable_reg_pp0_iter12))) begin
        grp_fu_374_p1 = ap_pipeline_reg_pp0_iter12_tmp_9_reg_1199;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter11))) begin
        grp_fu_374_p1 = ap_pipeline_reg_pp0_iter10_tmp_8_reg_1194;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter10))) begin
        grp_fu_374_p1 = ap_pipeline_reg_pp0_iter9_tmp_7_reg_1189;
    end else begin
        grp_fu_374_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_378_p0 = a_load_12_reg_1169;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_378_p0 = a_load_10_reg_1139;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_378_p0 = a_load_8_reg_1104;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_378_p0 = a_load_6_reg_1054;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_378_p0 = a_load_4_reg_989;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_378_p0 = a_load_2_reg_922;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_378_p0 = a_load_reg_862;
    end else begin
        grp_fu_378_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_378_p1 = b_load_12_reg_1154;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_378_p1 = b_load_10_reg_1119;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_378_p1 = b_load_8_reg_1069;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_378_p1 = b_load_6_reg_1004;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_378_p1 = b_load_4_reg_937;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_378_p1 = b_load_2_reg_877;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_378_p1 = b_load_reg_817;
    end else begin
        grp_fu_378_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_382_p0 = a_load_11_reg_1144;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_382_p0 = a_load_9_reg_1109;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_382_p0 = a_load_7_reg_1059;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_382_p0 = a_load_5_reg_994;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_382_p0 = a_load_3_reg_927;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_382_p0 = a_load_1_reg_867;
    end else begin
        grp_fu_382_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_382_p1 = b_load_11_reg_1149;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_382_p1 = b_load_9_reg_1114;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        grp_fu_382_p1 = b_load_7_reg_1064;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_382_p1 = b_load_5_reg_999;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_382_p1 = b_load_3_reg_932;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_382_p1 = b_load_1_reg_872;
    end else begin
        grp_fu_382_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        i_phi_fu_351_p4 = i_cast2_mid2_v_reg_717;
    end else begin
        i_phi_fu_351_p4 = i_reg_347;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        indvar_flatten_phi_fu_340_p4 = indvar_flatten_next_reg_702;
    end else begin
        indvar_flatten_phi_fu_340_p4 = indvar_flatten_reg_336;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_698 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        j_phi_fu_362_p4 = j_1_reg_1009;
    end else begin
        j_phi_fu_362_p4 = j_reg_358;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter18) & ~(1'b1 == ap_enable_reg_pp0_iter17)) & ~((1'b1 == ap_enable_reg_pp0_iter0) & ~(exitcond_flatten_fu_386_p2 == 1'b0) & ~(1'b1 == ap_enable_reg_pp0_iter1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b1 == ap_enable_reg_pp0_iter0) & ~(exitcond_flatten_fu_386_p2 == 1'b0) & ~(1'b1 == ap_enable_reg_pp0_iter1))) begin
                ap_NS_fsm = ap_ST_fsm_state129;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state129;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage2;
        end
        ap_ST_fsm_pp0_stage2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage3;
        end
        ap_ST_fsm_pp0_stage3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage4;
        end
        ap_ST_fsm_pp0_stage4 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage5;
        end
        ap_ST_fsm_pp0_stage5 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage6;
        end
        ap_ST_fsm_pp0_stage6 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[ap_const_lv32_2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[ap_const_lv32_3];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[ap_const_lv32_4];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[ap_const_lv32_5];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[ap_const_lv32_6];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[ap_const_lv32_7];

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state129 = ap_CS_fsm[ap_const_lv32_8];

assign c_address0 = tmp_37_cast_fu_694_p1;

assign c_d0 = sum_mult_1_11_reg_1279;

assign exitcond_flatten_fu_386_p2 = ((indvar_flatten_phi_fu_340_p4 == ap_const_lv8_A9) ? 1'b1 : 1'b0);

assign exitcond_fu_404_p2 = ((j_phi_fu_362_p4 == ap_const_lv4_D) ? 1'b1 : 1'b0);

assign i_1_fu_398_p2 = (ap_const_lv4_1 + i_phi_fu_351_p4);

assign i_cast2_mid2_v_fu_418_p3 = ((exitcond_fu_404_p2[0:0] === 1'b1) ? i_1_fu_398_p2 : i_phi_fu_351_p4);

assign indvar_flatten_next_fu_392_p2 = (indvar_flatten_phi_fu_340_p4 + ap_const_lv8_1);

assign j_1_fu_624_p2 = (ap_const_lv4_1 + j_mid2_reg_707);

assign j_cast1_cast4_cast_fu_449_p1 = j_mid2_reg_707;

assign j_cast1_cast4_fu_485_p1 = j_mid2_reg_707;

assign j_cast1_cast5_fu_597_p1 = j_mid2_reg_707;

assign j_cast1_cast_fu_452_p1 = j_mid2_reg_707;

assign j_cast1_fu_445_p1 = j_mid2_reg_707;

assign j_mid2_fu_410_p3 = ((exitcond_fu_404_p2[0:0] === 1'b1) ? ap_const_lv4_0 : j_phi_fu_362_p4);

assign tmp_13_cast_fu_471_p1 = tmp_13_reg_744;

assign tmp_13_fu_439_p2 = (ap_const_lv8_1 + tmp_38_fu_435_p1);

assign tmp_14_cast_fu_507_p1 = tmp_14_reg_780;

assign tmp_14_fu_475_p2 = (ap_const_lv8_2 + tmp_38_reg_728);

assign tmp_15_cast_fu_511_p1 = tmp_15_reg_785;

assign tmp_15_fu_480_p2 = (ap_const_lv8_3 + tmp_38_reg_728);

assign tmp_16_cast_fu_543_p1 = tmp_16_reg_832;

assign tmp_16_fu_515_p2 = (ap_const_lv8_4 + tmp_38_reg_728);

assign tmp_17_cast_fu_547_p1 = tmp_17_reg_837;

assign tmp_17_fu_520_p2 = (ap_const_lv8_5 + tmp_38_reg_728);

assign tmp_18_cast_fu_579_p1 = tmp_18_reg_892;

assign tmp_18_fu_551_p2 = (ap_const_lv8_6 + tmp_38_reg_728);

assign tmp_19_cast_fu_583_p1 = tmp_19_reg_897;

assign tmp_19_fu_556_p2 = (ap_const_lv8_7 + tmp_38_reg_728);

assign tmp_20_cast_fu_629_p1 = tmp_20_reg_952;

assign tmp_20_fu_587_p2 = (ap_const_lv8_8 + tmp_38_reg_728);

assign tmp_21_cast_fu_633_p1 = tmp_21_reg_957;

assign tmp_21_fu_592_p2 = (ap_const_lv8_9 + tmp_38_reg_728);

assign tmp_22_cast_fu_665_p1 = tmp_22_reg_1024;

assign tmp_22_fu_637_p2 = (ap_const_lv8_A + tmp_38_reg_728);

assign tmp_23_cast_fu_669_p1 = tmp_23_reg_1029;

assign tmp_23_fu_642_p2 = (ap_const_lv8_B + tmp_38_reg_728);

assign tmp_24_cast_fu_690_p1 = tmp_24_reg_1084;

assign tmp_24_fu_673_p2 = (ap_const_lv8_C + tmp_38_reg_728);

assign tmp_25_cast_fu_488_p1 = tmp_25_reg_760;

assign tmp_25_fu_455_p2 = (ap_const_lv5_D + j_cast1_cast_fu_452_p1);

assign tmp_26_cast_fu_492_p1 = tmp_26_reg_765;

assign tmp_26_fu_461_p2 = (ap_const_lv6_1A + j_cast1_cast4_cast_fu_449_p1);

assign tmp_27_cast_fu_525_p1 = tmp_27_reg_807;

assign tmp_27_fu_496_p2 = ($signed(ap_const_lv6_27) + $signed(j_cast1_cast4_cast_reg_749));

assign tmp_28_cast_fu_529_p1 = tmp_28_reg_812;

assign tmp_28_fu_501_p2 = (ap_const_lv7_34 + j_cast1_cast4_fu_485_p1);

assign tmp_29_cast_fu_561_p1 = tmp_29_reg_852;

assign tmp_29_fu_533_p2 = ($signed(ap_const_lv7_41) + $signed(j_cast1_cast4_reg_790));

assign tmp_30_cast_fu_565_p1 = tmp_30_reg_857;

assign tmp_30_fu_538_p2 = ($signed(ap_const_lv7_4E) + $signed(j_cast1_cast4_reg_790));

assign tmp_31_cast_fu_600_p1 = tmp_31_reg_912;

assign tmp_31_fu_569_p2 = ($signed(ap_const_lv7_5B) + $signed(j_cast1_cast4_reg_790));

assign tmp_32_cast7_fu_604_p1 = $signed(tmp_32_reg_917);

assign tmp_32_cast_fu_607_p1 = $unsigned(tmp_32_cast7_fu_604_p1);

assign tmp_32_fu_574_p2 = ($signed(ap_const_lv6_28) + $signed(j_cast1_cast4_cast_reg_749));

assign tmp_33_cast_fu_647_p1 = tmp_33_reg_979;

assign tmp_33_fu_612_p2 = (ap_const_lv8_75 + j_cast1_cast5_fu_597_p1);

assign tmp_34_cast_fu_651_p1 = tmp_34_reg_984;

assign tmp_34_fu_618_p2 = ($signed(ap_const_lv8_82) + $signed(j_cast1_cast5_fu_597_p1));

assign tmp_35_cast_fu_678_p1 = tmp_35_reg_1044;

assign tmp_35_fu_655_p2 = ($signed(ap_const_lv8_8F) + $signed(j_cast1_cast5_reg_962));

assign tmp_36_cast_fu_682_p1 = tmp_36_reg_1049;

assign tmp_36_fu_660_p2 = ($signed(ap_const_lv8_9C) + $signed(j_cast1_cast5_reg_962));

assign tmp_37_cast_fu_694_p1 = ap_pipeline_reg_pp0_iter17_tmp_37_reg_1099;

assign tmp_37_fu_686_p2 = (tmp_38_reg_728 + j_cast1_cast5_reg_962);

assign tmp_38_fu_435_p1 = tmp_fu_429_p2[7:0];

assign tmp_cast_fu_467_p1 = tmp_reg_723;

assign tmp_fu_429_p1 = tmp_fu_429_p10;

assign tmp_fu_429_p10 = i_cast2_mid2_v_reg_717;

assign tmp_fu_429_p2 = (ap_const_lv9_D * tmp_fu_429_p1);

always @ (posedge ap_clk) begin
    j_cast1_cast4_cast_reg_749[5:4] <= 2'b00;
    j_cast1_cast4_reg_790[6:4] <= 3'b000;
    j_cast1_cast5_reg_962[7:4] <= 4'b0000;
end

endmodule //matmul
